/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using ClickSend.Api;
using ClickSend.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace ClickSend.Test.Api
{
    /// <summary>
    ///  Class for testing EmailToSmsApi
    /// </summary>
    public sealed class EmailToSmsApiTests : ApiTestsBase
    {
        private readonly IEmailToSmsApi _instance;

        public EmailToSmsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IEmailToSmsApi>();
        }

        /// <summary>
        /// Test AddAllowedEmail
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AddAllowedEmailAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<AddAllowedEmailRequest> addAllowedEmailRequest = default!;
            var response = await _instance.AddAllowedEmailAsync(contentType, addAllowedEmailRequest);
            var model = response.Ok();
            Assert.IsType<AddAllowedEmail>(model);
        }

        /// <summary>
        /// Test CreateStrippedStringRule
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateStrippedStringRuleAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CreateStrippedStringRuleRequest> createStrippedStringRuleRequest = default!;
            var response = await _instance.CreateStrippedStringRuleAsync(contentType, createStrippedStringRuleRequest);
            var model = response.Ok();
            Assert.IsType<CreateStrippedStringRule>(model);
        }

        /// <summary>
        /// Test DeleteStrippedStringRule
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteStrippedStringRuleAsyncTest()
        {
            string ruleId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.DeleteStrippedStringRuleAsync(ruleId, contentType);
            var model = response.Ok();
            Assert.IsType<DeleteStrippedStringRule>(model);
        }

        /// <summary>
        /// Test UpdateStrippedStringRule
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateStrippedStringRuleAsyncTest()
        {
            string ruleId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<CreateStrippedStringRuleRequest> createStrippedStringRuleRequest = default!;
            var response = await _instance.UpdateStrippedStringRuleAsync(ruleId, contentType, createStrippedStringRuleRequest);
            var model = response.Ok();
            Assert.IsType<UpdateStrippedStringRule>(model);
        }

        /// <summary>
        /// Test ViewAllowedEmails
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewAllowedEmailsAsyncTest()
        {
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewAllowedEmailsAsync(contentType);
            var model = response.Ok();
            Assert.IsType<ViewAllowedEmails>(model);
        }

        /// <summary>
        /// Test ViewStrippedStringRule
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewStrippedStringRuleAsyncTest()
        {
            string ruleId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewStrippedStringRuleAsync(ruleId, contentType);
            var model = response.Ok();
            Assert.IsType<ViewStrippedStringRule>(model);
        }

        /// <summary>
        /// Test ViewStrippedStringRules
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewStrippedStringRulesAsyncTest()
        {
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewStrippedStringRulesAsync(contentType);
            var model = response.Ok();
            Assert.IsType<ViewStrippedStringRules>(model);
        }
    }
}
