/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using ClickSend.Api;
using ClickSend.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace ClickSend.Test.Api
{
    /// <summary>
    ///  Class for testing LettersApi
    /// </summary>
    public sealed class LettersApiTests : ApiTestsBase
    {
        private readonly ILettersApi _instance;

        public LettersApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ILettersApi>();
        }

        /// <summary>
        /// Test CalculateLetterPrice
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CalculateLetterPriceAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CalculateLetterPriceRequest> calculateLetterPriceRequest = default!;
            var response = await _instance.CalculateLetterPriceAsync(contentType, calculateLetterPriceRequest);
            var model = response.Ok();
            Assert.IsType<CalculateLetterPrice>(model);
        }

        /// <summary>
        /// Test CancelScheduledLetter
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CancelScheduledLetterAsyncTest()
        {
            string messageId = default!;
            var response = await _instance.CancelScheduledLetterAsync(messageId);
            var model = response.Ok();
            Assert.IsType<CancelScheduledLetter>(model);
        }

        /// <summary>
        /// Test DetectAddress
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DetectAddressAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<Object> body = default!;
            var response = await _instance.DetectAddressAsync(contentType, body);
            var model = response.Ok();
            Assert.IsType<DetectAddress>(model);
        }

        /// <summary>
        /// Test ExportLetterHistory
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ExportLetterHistoryAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<string> filename = default!;
            Client.Option<string> q = default!;
            Client.Option<string> orderBy = default!;
            Client.Option<string> dateFrom = default!;
            Client.Option<string> dateTo = default!;
            Client.Option<int> limit = default!;
            var response = await _instance.ExportLetterHistoryAsync(contentType, filename, q, orderBy, dateFrom, dateTo, limit);
            var model = response.Ok();
            Assert.IsType<ExportLetterHistory>(model);
        }

        /// <summary>
        /// Test SendLetter
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task SendLetterAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<SendLetterRequest> sendLetterRequest = default!;
            var response = await _instance.SendLetterAsync(contentType, sendLetterRequest);
            var model = response.Ok();
            Assert.IsType<SendLetter>(model);
        }

        /// <summary>
        /// Test ViewLetterHistory
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewLetterHistoryAsyncTest()
        {
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewLetterHistoryAsync(contentType);
            var model = response.Ok();
            Assert.IsType<ViewLetterHistory>(model);
        }
    }
}
