/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using ClickSend.Api;
using ClickSend.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace ClickSend.Test.Api
{
    /// <summary>
    ///  Class for testing ListsApi
    /// </summary>
    public sealed class ListsApiTests : ApiTestsBase
    {
        private readonly IListsApi _instance;

        public ListsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IListsApi>();
        }

        /// <summary>
        /// Test CopyContactToList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CopyContactToListAsyncTest()
        {
            string fromListId = default!;
            string contactId = default!;
            string toListId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<Object> body = default!;
            var response = await _instance.CopyContactToListAsync(fromListId, contactId, toListId, contentType, body);
            var model = response.Ok();
            Assert.IsType<CopyContactToList>(model);
        }

        /// <summary>
        /// Test CreateList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateListAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CreateListRequest> createListRequest = default!;
            var response = await _instance.CreateListAsync(contentType, createListRequest);
            var model = response.Ok();
            Assert.IsType<CreateList>(model);
        }

        /// <summary>
        /// Test CreateNewContact
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateNewContactAsyncTest()
        {
            string listId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<CreateNewContactRequest> createNewContactRequest = default!;
            var response = await _instance.CreateNewContactAsync(listId, contentType, createNewContactRequest);
            var model = response.Ok();
            Assert.IsType<CreateNewContact>(model);
        }

        /// <summary>
        /// Test DeleteList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteListAsyncTest()
        {
            string listId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.DeleteListAsync(listId, contentType);
            var model = response.Ok();
            Assert.IsType<DeleteList>(model);
        }

        /// <summary>
        /// Test ImportContacts
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ImportContactsAsyncTest()
        {
            string listId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<ImportContactsRequest> importContactsRequest = default!;
            var response = await _instance.ImportContactsAsync(listId, contentType, importContactsRequest);
            var model = response.Ok();
            Assert.IsType<ImportContacts>(model);
        }

        /// <summary>
        /// Test RemoveDuplicateContacts
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RemoveDuplicateContactsAsyncTest()
        {
            string listId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<RemoveDuplicateContactsRequest> removeDuplicateContactsRequest = default!;
            var response = await _instance.RemoveDuplicateContactsAsync(listId, contentType, removeDuplicateContactsRequest);
            var model = response.Ok();
            Assert.IsType<RemoveDuplicateContacts>(model);
        }

        /// <summary>
        /// Test RemoveOptedOutContacts
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RemoveOptedOutContactsAsyncTest()
        {
            string listId = default!;
            string optOutListId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<Object> body = default!;
            var response = await _instance.RemoveOptedOutContactsAsync(listId, optOutListId, contentType, body);
            var model = response.Ok();
            Assert.IsType<RemoveOptedOutContacts>(model);
        }

        /// <summary>
        /// Test TransferContactToList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TransferContactToListAsyncTest()
        {
            string fromListId = default!;
            string contactId = default!;
            string toListId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<Object> body = default!;
            var response = await _instance.TransferContactToListAsync(fromListId, contactId, toListId, contentType, body);
            var model = response.Ok();
            Assert.IsType<TransferContactToList>(model);
        }

        /// <summary>
        /// Test UpdateList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateListAsyncTest()
        {
            string listId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<CreateListRequest> createListRequest = default!;
            var response = await _instance.UpdateListAsync(listId, contentType, createListRequest);
            var model = response.Ok();
            Assert.IsType<UpdateList>(model);
        }

        /// <summary>
        /// Test ViewContactLists
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewContactListsAsyncTest()
        {
            Client.Option<string> q = default!;
            await _instance.ViewContactListsAsync(q);
        }

        /// <summary>
        /// Test ViewListContacts
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewListContactsAsyncTest()
        {
            string listId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewListContactsAsync(listId, contentType);
            var model = response.Ok();
            Assert.IsType<ViewListContacts>(model);
        }

        /// <summary>
        /// Test ViewLists
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewListsAsyncTest()
        {
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewListsAsync(contentType);
            var model = response.Ok();
            Assert.IsType<ViewLists>(model);
        }

        /// <summary>
        /// Test ViewSpecificList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewSpecificListAsyncTest()
        {
            string listId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewSpecificListAsync(listId, contentType);
            var model = response.Ok();
            Assert.IsType<ViewSpecificList>(model);
        }
    }
}
