/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using ClickSend.Api;
using ClickSend.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace ClickSend.Test.Api
{
    /// <summary>
    ///  Class for testing SmsApi
    /// </summary>
    public sealed class SmsApiTests : ApiTestsBase
    {
        private readonly ISmsApi _instance;

        public SmsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ISmsApi>();
        }

        /// <summary>
        /// Test CalculateSmsPrice
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CalculateSmsPriceAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CalculateSmsPriceRequest> calculateSmsPriceRequest = default!;
            var response = await _instance.CalculateSmsPriceAsync(contentType, calculateSmsPriceRequest);
            var model = response.Ok();
            Assert.IsType<CalculateSmsPrice>(model);
        }

        /// <summary>
        /// Test CancelAllSms
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CancelAllSmsAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CancelAllSmsRequest> cancelAllSmsRequest = default!;
            var response = await _instance.CancelAllSmsAsync(contentType, cancelAllSmsRequest);
            var model = response.Ok();
            Assert.IsType<CancelAllSms>(model);
        }

        /// <summary>
        /// Test CancelSms
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CancelSmsAsyncTest()
        {
            string messageId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.CancelSmsAsync(messageId, contentType);
            var model = response.Ok();
            Assert.IsType<CancelSms>(model);
        }

        /// <summary>
        /// Test CreateSmsDeliveryReceiptRule
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateSmsDeliveryReceiptRuleAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CreateSmsDeliveryReceiptRuleRequest> createSmsDeliveryReceiptRuleRequest = default!;
            var response = await _instance.CreateSmsDeliveryReceiptRuleAsync(contentType, createSmsDeliveryReceiptRuleRequest);
            var model = response.Ok();
            Assert.IsType<CreateSmsDeliveryReceiptRule>(model);
        }

        /// <summary>
        /// Test CreateSmsInboundAutomation
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateSmsInboundAutomationAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CreateSmsInboundAutomationRequest> createSmsInboundAutomationRequest = default!;
            var response = await _instance.CreateSmsInboundAutomationAsync(contentType, createSmsInboundAutomationRequest);
            var model = response.Ok();
            Assert.IsType<CreateSmsInboundAutomation>(model);
        }

        /// <summary>
        /// Test CreateSmsTemplate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateSmsTemplateAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CreateSmsTemplateRequest> createSmsTemplateRequest = default!;
            var response = await _instance.CreateSmsTemplateAsync(contentType, createSmsTemplateRequest);
            var model = response.Ok();
            Assert.IsType<CreateSmsTemplate>(model);
        }

        /// <summary>
        /// Test CreateTestInboundSms
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateTestInboundSmsAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CreateTestInboundSmsRequest> createTestInboundSmsRequest = default!;
            var response = await _instance.CreateTestInboundSmsAsync(contentType, createTestInboundSmsRequest);
            var model = response.Ok();
            Assert.IsType<CreateTestInboundSms>(model);
        }

        /// <summary>
        /// Test CreateTestSmsReceipt
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateTestSmsReceiptAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<CreateTestSmsReceiptRequest> createTestSmsReceiptRequest = default!;
            var response = await _instance.CreateTestSmsReceiptAsync(contentType, createTestSmsReceiptRequest);
            var model = response.Ok();
            Assert.IsType<CreateTestSmsReceipt>(model);
        }

        /// <summary>
        /// Test DeleteSmsDeliveryReceiptRule
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteSmsDeliveryReceiptRuleAsyncTest()
        {
            string receiptRuleId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.DeleteSmsDeliveryReceiptRuleAsync(receiptRuleId, contentType);
            var model = response.Ok();
            Assert.IsType<DeleteSmsDeliveryReceiptRule>(model);
        }

        /// <summary>
        /// Test DeleteSmsInboundAutomation
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteSmsInboundAutomationAsyncTest()
        {
            string inboundRuleId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.DeleteSmsInboundAutomationAsync(inboundRuleId, contentType);
            var model = response.Ok();
            Assert.IsType<DeleteSmsInboundAutomation>(model);
        }

        /// <summary>
        /// Test DeleteSmsTemplate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteSmsTemplateAsyncTest()
        {
            string templateId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.DeleteSmsTemplateAsync(templateId, contentType);
            var model = response.Ok();
            Assert.IsType<DeleteSmsTemplate>(model);
        }

        /// <summary>
        /// Test ExportSmsHistory
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ExportSmsHistoryAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<string> filename = default!;
            Client.Option<int> page = default!;
            Client.Option<int> limit = default!;
            Client.Option<string> q = default!;
            Client.Option<string> orderBy = default!;
            Client.Option<int> dateFrom = default!;
            Client.Option<int> dateTo = default!;
            var response = await _instance.ExportSmsHistoryAsync(contentType, filename, page, limit, q, orderBy, dateFrom, dateTo);
            var model = response.Ok();
            Assert.IsType<ExportSmsHistory>(model);
        }

        /// <summary>
        /// Test MarkInboundSmsAsRead
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task MarkInboundSmsAsReadAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<MarkSmsReceiptAsReadRequest> markSmsReceiptAsReadRequest = default!;
            var response = await _instance.MarkInboundSmsAsReadAsync(contentType, markSmsReceiptAsReadRequest);
            var model = response.Ok();
            Assert.IsType<MarkInboundSmsAsRead>(model);
        }

        /// <summary>
        /// Test MarkSmsReceiptAsRead
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task MarkSmsReceiptAsReadAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<MarkSmsReceiptAsReadRequest> markSmsReceiptAsReadRequest = default!;
            var response = await _instance.MarkSmsReceiptAsReadAsync(contentType, markSmsReceiptAsReadRequest);
            var model = response.Ok();
            Assert.IsType<MarkSmsReceiptAsRead>(model);
        }

        /// <summary>
        /// Test MarkSpecificInboundSmsMessageAsRead
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task MarkSpecificInboundSmsMessageAsReadAsyncTest()
        {
            string messageId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.MarkSpecificInboundSmsMessageAsReadAsync(messageId, contentType);
            var model = response.Ok();
            Assert.IsType<MarkSpecificInboundSmsMessageAsRead>(model);
        }

        /// <summary>
        /// Test SendSms
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task SendSmsAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<SendSmsRequest> sendSmsRequest = default!;
            var response = await _instance.SendSmsAsync(contentType, sendSmsRequest);
            var model = response.Ok();
            Assert.IsType<SendSms>(model);
        }

        /// <summary>
        /// Test UpdateSmsDeliveryReceiptRule
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateSmsDeliveryReceiptRuleAsyncTest()
        {
            string receiptRuleId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<CreateSmsDeliveryReceiptRuleRequest> createSmsDeliveryReceiptRuleRequest = default!;
            var response = await _instance.UpdateSmsDeliveryReceiptRuleAsync(receiptRuleId, contentType, createSmsDeliveryReceiptRuleRequest);
            var model = response.Ok();
            Assert.IsType<UpdateSmsDeliveryReceiptRule>(model);
        }

        /// <summary>
        /// Test UpdateSmsInboundAutomation
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateSmsInboundAutomationAsyncTest()
        {
            string inboundRuleId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<UpdateSmsInboundAutomationRequest> updateSmsInboundAutomationRequest = default!;
            var response = await _instance.UpdateSmsInboundAutomationAsync(inboundRuleId, contentType, updateSmsInboundAutomationRequest);
            var model = response.Ok();
            Assert.IsType<UpdateSmsInboundAutomation>(model);
        }

        /// <summary>
        /// Test UpdateSmsTemplate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateSmsTemplateAsyncTest()
        {
            string templateId = default!;
            Client.Option<string> contentType = default!;
            Client.Option<CreateSmsTemplateRequest> createSmsTemplateRequest = default!;
            var response = await _instance.UpdateSmsTemplateAsync(templateId, contentType, createSmsTemplateRequest);
            var model = response.Ok();
            Assert.IsType<UpdateSmsTemplate>(model);
        }

        /// <summary>
        /// Test ViewASpecificInboundSmsMessage
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewASpecificInboundSmsMessageAsyncTest()
        {
            string originalMessageId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewASpecificInboundSmsMessageAsync(originalMessageId, contentType);
            var model = response.Ok();
            Assert.IsType<ViewASpecificInboundSmsMessage>(model);
        }

        /// <summary>
        /// Test ViewASpecificSmsTemplate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewASpecificSmsTemplateAsyncTest()
        {
            string templateId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewASpecificSmsTemplateAsync(templateId, contentType);
            var model = response.Ok();
            Assert.IsType<ViewASpecificSmsTemplate>(model);
        }

        /// <summary>
        /// Test ViewInboundSms
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewInboundSmsAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<int> page = default!;
            Client.Option<int> limit = default!;
            var response = await _instance.ViewInboundSmsAsync(contentType, page, limit);
            var model = response.Ok();
            Assert.IsType<ViewInboundSms>(model);
        }

        /// <summary>
        /// Test ViewSmsDeliveryReceiptRule
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewSmsDeliveryReceiptRuleAsyncTest()
        {
            string receiptRuleId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewSmsDeliveryReceiptRuleAsync(receiptRuleId, contentType);
            var model = response.Ok();
            Assert.IsType<ViewSmsDeliveryReceiptRule>(model);
        }

        /// <summary>
        /// Test ViewSmsDeliveryReceiptRules
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewSmsDeliveryReceiptRulesAsyncTest()
        {
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewSmsDeliveryReceiptRulesAsync(contentType);
            var model = response.Ok();
            Assert.IsType<ViewSmsDeliveryReceiptRules>(model);
        }

        /// <summary>
        /// Test ViewSmsHistory
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewSmsHistoryAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<int> page = default!;
            Client.Option<int> limit = default!;
            Client.Option<string> q = default!;
            Client.Option<string> orderBy = default!;
            Client.Option<int> dateFrom = default!;
            Client.Option<int> dateTo = default!;
            var response = await _instance.ViewSmsHistoryAsync(contentType, page, limit, q, orderBy, dateFrom, dateTo);
            var model = response.Ok();
            Assert.IsType<ViewSmsHistory>(model);
        }

        /// <summary>
        /// Test ViewSmsInboundAutomation
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewSmsInboundAutomationAsyncTest()
        {
            string inboundRuleId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewSmsInboundAutomationAsync(inboundRuleId, contentType);
            var model = response.Ok();
            Assert.IsType<ViewSmsInboundAutomation>(model);
        }

        /// <summary>
        /// Test ViewSmsInboundAutomations
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewSmsInboundAutomationsAsyncTest()
        {
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewSmsInboundAutomationsAsync(contentType);
            var model = response.Ok();
            Assert.IsType<ViewSmsInboundAutomations>(model);
        }

        /// <summary>
        /// Test ViewSmsReceipts
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewSmsReceiptsAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<int> page = default!;
            Client.Option<int> limit = default!;
            var response = await _instance.ViewSmsReceiptsAsync(contentType, page, limit);
            var model = response.Ok();
            Assert.IsType<ViewSmsReceipts>(model);
        }

        /// <summary>
        /// Test ViewSmsTemplates
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewSmsTemplatesAsyncTest()
        {
            Client.Option<string> contentType = default!;
            Client.Option<int> page = default!;
            Client.Option<int> limit = default!;
            Client.Option<string> q = default!;
            Client.Option<string> orderBy = default!;
            var response = await _instance.ViewSmsTemplatesAsync(contentType, page, limit, q, orderBy);
            var model = response.Ok();
            Assert.IsType<ViewSmsTemplates>(model);
        }

        /// <summary>
        /// Test ViewSpecificSmsReceipt
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ViewSpecificSmsReceiptAsyncTest()
        {
            string messageId = default!;
            Client.Option<string> contentType = default!;
            var response = await _instance.ViewSpecificSmsReceiptAsync(messageId, contentType);
            var model = response.Ok();
            Assert.IsType<ViewSpecificSmsReceipt>(model);
        }
    }
}
