// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// The country of the receipient in two-letter format (e.g. US, UK, AU, NZ, etc).
    /// </summary>
    public partial class CalculateSmsPriceDataSummaryCountriesInnerCountry : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CalculateSmsPriceDataSummaryCountriesInnerCountry" /> class.
        /// </summary>
        /// <param name="registrationType">The global sending requirement for this country. It can be one of the following:  - **0:** No number or account registration required.      - **1:** Number registration required. You can purchase a registered number from ClickSend. Examples: US and CA.      - **2:** Account registration required. You can register your company details or business details to register your account. Examples: NZ, SG and UAE.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;This parameter is fixed and can&#39;t be changed based on your settings.&lt;/p&gt; &lt;/div&gt;</param>
        /// <param name="receipientCount">The number of messages you are sending to this country. The system can count up to 1000 messages.</param>
        /// <param name="usableSenderId">Indicates whether you have a usable ***Sender ID** for this country:  - **True:** A **Sender ID** is available for you to use.      - **False:** No **Sender ID** is available for you to use.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;     &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;     &lt;p&gt;Countries with &lt;em&gt;registration_type&lt;/em&gt; set to &lt;strong&gt;0&lt;/strong&gt; will have the &lt;em&gt;usable_sender_id&lt;/em&gt; set as &lt;strong&gt;True&lt;/strong&gt;, and messages will be sent from shared numbers.&lt;/p&gt; &lt;/div&gt;</param>
        /// <param name="selected">Indicates whether you have enabled the global sending for this country:  - **True:** You have selected this country for global sending and can send messages here.      - **False:** You haven’t selected this country for global sending and can’t send messages here.</param>
        /// <param name="name">The name of the country.</param>
        /// <param name="regulation">regulation</param>
        /// <param name="registrationStatusId">Your current registration status for this country. This parameter is used by the internal team to track the status of your registration.</param>
        /// <param name="registrationEntityId">The global sending requirement for this country. It can be one of the following:  - **0:** No number or account registration required.      - **1:** Number registration required. You can purchase a registered number from ClickSend. Examples: US and CA.      - **2:** Account registration required. You can register your company details or business details to register your account. Examples: NZ, SG and UAE.    This parameter is a duplicate of registration_type. It determines which form you need for the global sending registration process.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;This parameter is static. Its value can’t change based on your settings.&lt;/p&gt; &lt;/div&gt;</param>
        /// <param name="jotformId">The Jotform identifier for your account. It’s used to track the global sending registration form. If it is **null**, no Jotform is assigned to you. It is used only for number and account registration.</param>
        [JsonConstructor]
        public CalculateSmsPriceDataSummaryCountriesInnerCountry(Option<int?> registrationType = default, Option<int?> receipientCount = default, Option<bool?> usableSenderId = default, Option<bool?> selected = default, Option<string?> name = default, Option<CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation?> regulation = default, Option<int?> registrationStatusId = default, Option<int?> registrationEntityId = default, Option<int?> jotformId = default)
        {
            RegistrationTypeOption = registrationType;
            ReceipientCountOption = receipientCount;
            UsableSenderIdOption = usableSenderId;
            SelectedOption = selected;
            NameOption = name;
            RegulationOption = regulation;
            RegistrationStatusIdOption = registrationStatusId;
            RegistrationEntityIdOption = registrationEntityId;
            JotformIdOption = jotformId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of RegistrationType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RegistrationTypeOption { get; private set; }

        /// <summary>
        /// The global sending requirement for this country. It can be one of the following:  - **0:** No number or account registration required.      - **1:** Number registration required. You can purchase a registered number from ClickSend. Examples: US and CA.      - **2:** Account registration required. You can register your company details or business details to register your account. Examples: NZ, SG and UAE.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;This parameter is fixed and can&#39;t be changed based on your settings.&lt;/p&gt; &lt;/div&gt;
        /// </summary>
        /// <value>The global sending requirement for this country. It can be one of the following:  - **0:** No number or account registration required.      - **1:** Number registration required. You can purchase a registered number from ClickSend. Examples: US and CA.      - **2:** Account registration required. You can register your company details or business details to register your account. Examples: NZ, SG and UAE.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;This parameter is fixed and can&#39;t be changed based on your settings.&lt;/p&gt; &lt;/div&gt;</value>
        [JsonPropertyName("registration_type")]
        public int? RegistrationType { get { return this.RegistrationTypeOption.Value; } set { this.RegistrationTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReceipientCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ReceipientCountOption { get; private set; }

        /// <summary>
        /// The number of messages you are sending to this country. The system can count up to 1000 messages.
        /// </summary>
        /// <value>The number of messages you are sending to this country. The system can count up to 1000 messages.</value>
        [JsonPropertyName("receipient_count")]
        public int? ReceipientCount { get { return this.ReceipientCountOption.Value; } set { this.ReceipientCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of UsableSenderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> UsableSenderIdOption { get; private set; }

        /// <summary>
        /// Indicates whether you have a usable ***Sender ID** for this country:  - **True:** A **Sender ID** is available for you to use.      - **False:** No **Sender ID** is available for you to use.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;     &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;     &lt;p&gt;Countries with &lt;em&gt;registration_type&lt;/em&gt; set to &lt;strong&gt;0&lt;/strong&gt; will have the &lt;em&gt;usable_sender_id&lt;/em&gt; set as &lt;strong&gt;True&lt;/strong&gt;, and messages will be sent from shared numbers.&lt;/p&gt; &lt;/div&gt;
        /// </summary>
        /// <value>Indicates whether you have a usable ***Sender ID** for this country:  - **True:** A **Sender ID** is available for you to use.      - **False:** No **Sender ID** is available for you to use.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;     &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;     &lt;p&gt;Countries with &lt;em&gt;registration_type&lt;/em&gt; set to &lt;strong&gt;0&lt;/strong&gt; will have the &lt;em&gt;usable_sender_id&lt;/em&gt; set as &lt;strong&gt;True&lt;/strong&gt;, and messages will be sent from shared numbers.&lt;/p&gt; &lt;/div&gt;</value>
        [JsonPropertyName("usable_sender_id")]
        public bool? UsableSenderId { get { return this.UsableSenderIdOption.Value; } set { this.UsableSenderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Selected
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SelectedOption { get; private set; }

        /// <summary>
        /// Indicates whether you have enabled the global sending for this country:  - **True:** You have selected this country for global sending and can send messages here.      - **False:** You haven’t selected this country for global sending and can’t send messages here.
        /// </summary>
        /// <value>Indicates whether you have enabled the global sending for this country:  - **True:** You have selected this country for global sending and can send messages here.      - **False:** You haven’t selected this country for global sending and can’t send messages here.</value>
        [JsonPropertyName("selected")]
        public bool? Selected { get { return this.SelectedOption.Value; } set { this.SelectedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// The name of the country.
        /// </summary>
        /// <value>The name of the country.</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Regulation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation?> RegulationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Regulation
        /// </summary>
        [JsonPropertyName("regulation")]
        public CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation? Regulation { get { return this.RegulationOption.Value; } set { this.RegulationOption = new(value); } }

        /// <summary>
        /// Used to track the state of RegistrationStatusId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RegistrationStatusIdOption { get; private set; }

        /// <summary>
        /// Your current registration status for this country. This parameter is used by the internal team to track the status of your registration.
        /// </summary>
        /// <value>Your current registration status for this country. This parameter is used by the internal team to track the status of your registration.</value>
        [JsonPropertyName("registration_status_id")]
        public int? RegistrationStatusId { get { return this.RegistrationStatusIdOption.Value; } set { this.RegistrationStatusIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of RegistrationEntityId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RegistrationEntityIdOption { get; private set; }

        /// <summary>
        /// The global sending requirement for this country. It can be one of the following:  - **0:** No number or account registration required.      - **1:** Number registration required. You can purchase a registered number from ClickSend. Examples: US and CA.      - **2:** Account registration required. You can register your company details or business details to register your account. Examples: NZ, SG and UAE.    This parameter is a duplicate of registration_type. It determines which form you need for the global sending registration process.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;This parameter is static. Its value can’t change based on your settings.&lt;/p&gt; &lt;/div&gt;
        /// </summary>
        /// <value>The global sending requirement for this country. It can be one of the following:  - **0:** No number or account registration required.      - **1:** Number registration required. You can purchase a registered number from ClickSend. Examples: US and CA.      - **2:** Account registration required. You can register your company details or business details to register your account. Examples: NZ, SG and UAE.    This parameter is a duplicate of registration_type. It determines which form you need for the global sending registration process.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;This parameter is static. Its value can’t change based on your settings.&lt;/p&gt; &lt;/div&gt;</value>
        [JsonPropertyName("registration_entity_id")]
        public int? RegistrationEntityId { get { return this.RegistrationEntityIdOption.Value; } set { this.RegistrationEntityIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of JotformId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> JotformIdOption { get; private set; }

        /// <summary>
        /// The Jotform identifier for your account. It’s used to track the global sending registration form. If it is **null**, no Jotform is assigned to you. It is used only for number and account registration.
        /// </summary>
        /// <value>The Jotform identifier for your account. It’s used to track the global sending registration form. If it is **null**, no Jotform is assigned to you. It is used only for number and account registration.</value>
        [JsonPropertyName("jotform_id")]
        public int? JotformId { get { return this.JotformIdOption.Value; } set { this.JotformIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CalculateSmsPriceDataSummaryCountriesInnerCountry {\n");
            sb.Append("  RegistrationType: ").Append(RegistrationType).Append("\n");
            sb.Append("  ReceipientCount: ").Append(ReceipientCount).Append("\n");
            sb.Append("  UsableSenderId: ").Append(UsableSenderId).Append("\n");
            sb.Append("  Selected: ").Append(Selected).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Regulation: ").Append(Regulation).Append("\n");
            sb.Append("  RegistrationStatusId: ").Append(RegistrationStatusId).Append("\n");
            sb.Append("  RegistrationEntityId: ").Append(RegistrationEntityId).Append("\n");
            sb.Append("  JotformId: ").Append(JotformId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CalculateSmsPriceDataSummaryCountriesInnerCountry" />
    /// </summary>
    public class CalculateSmsPriceDataSummaryCountriesInnerCountryJsonConverter : JsonConverter<CalculateSmsPriceDataSummaryCountriesInnerCountry>
    {
        /// <summary>
        /// Deserializes json to <see cref="CalculateSmsPriceDataSummaryCountriesInnerCountry" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CalculateSmsPriceDataSummaryCountriesInnerCountry Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> registrationType = default;
            Option<int?> receipientCount = default;
            Option<bool?> usableSenderId = default;
            Option<bool?> selected = default;
            Option<string?> name = default;
            Option<CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation?> regulation = default;
            Option<int?> registrationStatusId = default;
            Option<int?> registrationEntityId = default;
            Option<int?> jotformId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "registration_type":
                            registrationType = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "receipient_count":
                            receipientCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "usable_sender_id":
                            usableSenderId = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "selected":
                            selected = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "regulation":
                            regulation = new Option<CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation?>(JsonSerializer.Deserialize<CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "registration_status_id":
                            registrationStatusId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "registration_entity_id":
                            registrationEntityId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "jotform_id":
                            jotformId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (registrationType.IsSet && registrationType.Value == null)
                throw new ArgumentNullException(nameof(registrationType), "Property is not nullable for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (receipientCount.IsSet && receipientCount.Value == null)
                throw new ArgumentNullException(nameof(receipientCount), "Property is not nullable for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (usableSenderId.IsSet && usableSenderId.Value == null)
                throw new ArgumentNullException(nameof(usableSenderId), "Property is not nullable for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (selected.IsSet && selected.Value == null)
                throw new ArgumentNullException(nameof(selected), "Property is not nullable for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (regulation.IsSet && regulation.Value == null)
                throw new ArgumentNullException(nameof(regulation), "Property is not nullable for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (registrationStatusId.IsSet && registrationStatusId.Value == null)
                throw new ArgumentNullException(nameof(registrationStatusId), "Property is not nullable for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (registrationEntityId.IsSet && registrationEntityId.Value == null)
                throw new ArgumentNullException(nameof(registrationEntityId), "Property is not nullable for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (jotformId.IsSet && jotformId.Value == null)
                throw new ArgumentNullException(nameof(jotformId), "Property is not nullable for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            return new CalculateSmsPriceDataSummaryCountriesInnerCountry(registrationType, receipientCount, usableSenderId, selected, name, regulation, registrationStatusId, registrationEntityId, jotformId);
        }

        /// <summary>
        /// Serializes a <see cref="CalculateSmsPriceDataSummaryCountriesInnerCountry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="calculateSmsPriceDataSummaryCountriesInnerCountry"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CalculateSmsPriceDataSummaryCountriesInnerCountry calculateSmsPriceDataSummaryCountriesInnerCountry, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, calculateSmsPriceDataSummaryCountriesInnerCountry, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CalculateSmsPriceDataSummaryCountriesInnerCountry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="calculateSmsPriceDataSummaryCountriesInnerCountry"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CalculateSmsPriceDataSummaryCountriesInnerCountry calculateSmsPriceDataSummaryCountriesInnerCountry, JsonSerializerOptions jsonSerializerOptions)
        {
            if (calculateSmsPriceDataSummaryCountriesInnerCountry.NameOption.IsSet && calculateSmsPriceDataSummaryCountriesInnerCountry.Name == null)
                throw new ArgumentNullException(nameof(calculateSmsPriceDataSummaryCountriesInnerCountry.Name), "Property is required for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (calculateSmsPriceDataSummaryCountriesInnerCountry.RegulationOption.IsSet && calculateSmsPriceDataSummaryCountriesInnerCountry.Regulation == null)
                throw new ArgumentNullException(nameof(calculateSmsPriceDataSummaryCountriesInnerCountry.Regulation), "Property is required for class CalculateSmsPriceDataSummaryCountriesInnerCountry.");

            if (calculateSmsPriceDataSummaryCountriesInnerCountry.RegistrationTypeOption.IsSet)
                writer.WriteNumber("registration_type", calculateSmsPriceDataSummaryCountriesInnerCountry.RegistrationTypeOption.Value!.Value);

            if (calculateSmsPriceDataSummaryCountriesInnerCountry.ReceipientCountOption.IsSet)
                writer.WriteNumber("receipient_count", calculateSmsPriceDataSummaryCountriesInnerCountry.ReceipientCountOption.Value!.Value);

            if (calculateSmsPriceDataSummaryCountriesInnerCountry.UsableSenderIdOption.IsSet)
                writer.WriteBoolean("usable_sender_id", calculateSmsPriceDataSummaryCountriesInnerCountry.UsableSenderIdOption.Value!.Value);

            if (calculateSmsPriceDataSummaryCountriesInnerCountry.SelectedOption.IsSet)
                writer.WriteBoolean("selected", calculateSmsPriceDataSummaryCountriesInnerCountry.SelectedOption.Value!.Value);

            if (calculateSmsPriceDataSummaryCountriesInnerCountry.NameOption.IsSet)
                writer.WriteString("name", calculateSmsPriceDataSummaryCountriesInnerCountry.Name);

            if (calculateSmsPriceDataSummaryCountriesInnerCountry.RegulationOption.IsSet)
            {
                writer.WritePropertyName("regulation");
                JsonSerializer.Serialize(writer, calculateSmsPriceDataSummaryCountriesInnerCountry.Regulation, jsonSerializerOptions);
            }
            if (calculateSmsPriceDataSummaryCountriesInnerCountry.RegistrationStatusIdOption.IsSet)
                writer.WriteNumber("registration_status_id", calculateSmsPriceDataSummaryCountriesInnerCountry.RegistrationStatusIdOption.Value!.Value);

            if (calculateSmsPriceDataSummaryCountriesInnerCountry.RegistrationEntityIdOption.IsSet)
                writer.WriteNumber("registration_entity_id", calculateSmsPriceDataSummaryCountriesInnerCountry.RegistrationEntityIdOption.Value!.Value);

            if (calculateSmsPriceDataSummaryCountriesInnerCountry.JotformIdOption.IsSet)
                writer.WriteNumber("jotform_id", calculateSmsPriceDataSummaryCountriesInnerCountry.JotformIdOption.Value!.Value);
        }
    }
}
