// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// CreateFaxInboundRuleRequest
    /// </summary>
    public partial class CreateFaxInboundRuleRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateFaxInboundRuleRequest" /> class.
        /// </summary>
        /// <param name="dedicatedNumber">dedicatedNumber</param>
        /// <param name="ruleName">ruleName</param>
        /// <param name="action">action</param>
        /// <param name="actionAddress">actionAddress</param>
        /// <param name="enabled">enabled</param>
        [JsonConstructor]
        public CreateFaxInboundRuleRequest(Option<string?> dedicatedNumber = default, Option<string?> ruleName = default, Option<string?> action = default, Option<string?> actionAddress = default, Option<int?> enabled = default)
        {
            DedicatedNumberOption = dedicatedNumber;
            RuleNameOption = ruleName;
            ActionOption = action;
            ActionAddressOption = actionAddress;
            EnabledOption = enabled;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of DedicatedNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DedicatedNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets DedicatedNumber
        /// </summary>
        [JsonPropertyName("dedicated_number")]
        public string? DedicatedNumber { get { return this.DedicatedNumberOption.Value; } set { this.DedicatedNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of RuleName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RuleNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets RuleName
        /// </summary>
        [JsonPropertyName("rule_name")]
        public string? RuleName { get { return this.RuleNameOption.Value; } set { this.RuleNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Action
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [JsonPropertyName("action")]
        public string? Action { get { return this.ActionOption.Value; } set { this.ActionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ActionAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActionAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets ActionAddress
        /// </summary>
        [JsonPropertyName("action_address")]
        public string? ActionAddress { get { return this.ActionAddressOption.Value; } set { this.ActionAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [JsonPropertyName("enabled")]
        public int? Enabled { get { return this.EnabledOption.Value; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateFaxInboundRuleRequest {\n");
            sb.Append("  DedicatedNumber: ").Append(DedicatedNumber).Append("\n");
            sb.Append("  RuleName: ").Append(RuleName).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  ActionAddress: ").Append(ActionAddress).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateFaxInboundRuleRequest" />
    /// </summary>
    public class CreateFaxInboundRuleRequestJsonConverter : JsonConverter<CreateFaxInboundRuleRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateFaxInboundRuleRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateFaxInboundRuleRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> dedicatedNumber = default;
            Option<string?> ruleName = default;
            Option<string?> action = default;
            Option<string?> actionAddress = default;
            Option<int?> enabled = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "dedicated_number":
                            dedicatedNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "rule_name":
                            ruleName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action":
                            action = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action_address":
                            actionAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "enabled":
                            enabled = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (dedicatedNumber.IsSet && dedicatedNumber.Value == null)
                throw new ArgumentNullException(nameof(dedicatedNumber), "Property is not nullable for class CreateFaxInboundRuleRequest.");

            if (ruleName.IsSet && ruleName.Value == null)
                throw new ArgumentNullException(nameof(ruleName), "Property is not nullable for class CreateFaxInboundRuleRequest.");

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class CreateFaxInboundRuleRequest.");

            if (actionAddress.IsSet && actionAddress.Value == null)
                throw new ArgumentNullException(nameof(actionAddress), "Property is not nullable for class CreateFaxInboundRuleRequest.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class CreateFaxInboundRuleRequest.");

            return new CreateFaxInboundRuleRequest(dedicatedNumber, ruleName, action, actionAddress, enabled);
        }

        /// <summary>
        /// Serializes a <see cref="CreateFaxInboundRuleRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createFaxInboundRuleRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateFaxInboundRuleRequest createFaxInboundRuleRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createFaxInboundRuleRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateFaxInboundRuleRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createFaxInboundRuleRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateFaxInboundRuleRequest createFaxInboundRuleRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createFaxInboundRuleRequest.DedicatedNumberOption.IsSet && createFaxInboundRuleRequest.DedicatedNumber == null)
                throw new ArgumentNullException(nameof(createFaxInboundRuleRequest.DedicatedNumber), "Property is required for class CreateFaxInboundRuleRequest.");

            if (createFaxInboundRuleRequest.RuleNameOption.IsSet && createFaxInboundRuleRequest.RuleName == null)
                throw new ArgumentNullException(nameof(createFaxInboundRuleRequest.RuleName), "Property is required for class CreateFaxInboundRuleRequest.");

            if (createFaxInboundRuleRequest.ActionOption.IsSet && createFaxInboundRuleRequest.Action == null)
                throw new ArgumentNullException(nameof(createFaxInboundRuleRequest.Action), "Property is required for class CreateFaxInboundRuleRequest.");

            if (createFaxInboundRuleRequest.ActionAddressOption.IsSet && createFaxInboundRuleRequest.ActionAddress == null)
                throw new ArgumentNullException(nameof(createFaxInboundRuleRequest.ActionAddress), "Property is required for class CreateFaxInboundRuleRequest.");

            if (createFaxInboundRuleRequest.DedicatedNumberOption.IsSet)
                writer.WriteString("dedicated_number", createFaxInboundRuleRequest.DedicatedNumber);

            if (createFaxInboundRuleRequest.RuleNameOption.IsSet)
                writer.WriteString("rule_name", createFaxInboundRuleRequest.RuleName);

            if (createFaxInboundRuleRequest.ActionOption.IsSet)
                writer.WriteString("action", createFaxInboundRuleRequest.Action);

            if (createFaxInboundRuleRequest.ActionAddressOption.IsSet)
                writer.WriteString("action_address", createFaxInboundRuleRequest.ActionAddress);

            if (createFaxInboundRuleRequest.EnabledOption.IsSet)
                writer.WriteNumber("enabled", createFaxInboundRuleRequest.EnabledOption.Value!.Value);
        }
    }
}
