// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// CreateDefaultSenderRequest
    /// </summary>
    public partial class CreateDefaultSenderRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDefaultSenderRequest" /> class.
        /// </summary>
        /// <param name="countryCode">The country code of the recipient. Must be a valid ISO 3166-1 alpha-2 country code.</param>
        /// <param name="productType">The type of product for the assignment. Support for additional types coming soon.</param>
        /// <param name="defaultSenderStrategies">Array detailing sender strategies. Must contain exactly 1 element. Multiple strategies support coming soon.</param>
        [JsonConstructor]
        public CreateDefaultSenderRequest(string countryCode, ProductTypeEnum productType, List<CreateDefaultSenderRequestDefaultSenderStrategiesInner> defaultSenderStrategies)
        {
            CountryCode = countryCode;
            ProductType = productType;
            DefaultSenderStrategies = defaultSenderStrategies;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The type of product for the assignment. Support for additional types coming soon.
        /// </summary>
        /// <value>The type of product for the assignment. Support for additional types coming soon.</value>
        public enum ProductTypeEnum
        {
            /// <summary>
            /// Enum SMS for value: SMS
            /// </summary>
            SMS = 1
        }

        /// <summary>
        /// Returns a <see cref="ProductTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ProductTypeEnum ProductTypeEnumFromString(string value)
        {
            if (value.Equals("SMS"))
                return ProductTypeEnum.SMS;

            throw new NotImplementedException($"Could not convert value to type ProductTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ProductTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ProductTypeEnum? ProductTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("SMS"))
                return ProductTypeEnum.SMS;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ProductTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ProductTypeEnumToJsonValue(ProductTypeEnum value)
        {
            if (value == ProductTypeEnum.SMS)
                return "SMS";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The type of product for the assignment. Support for additional types coming soon.
        /// </summary>
        /// <value>The type of product for the assignment. Support for additional types coming soon.</value>
        [JsonPropertyName("product_type")]
        public ProductTypeEnum ProductType { get; set; }

        /// <summary>
        /// The country code of the recipient. Must be a valid ISO 3166-1 alpha-2 country code.
        /// </summary>
        /// <value>The country code of the recipient. Must be a valid ISO 3166-1 alpha-2 country code.</value>
        /* <example>AU</example> */
        [JsonPropertyName("country_code")]
        public string CountryCode { get; set; }

        /// <summary>
        /// Array detailing sender strategies. Must contain exactly 1 element. Multiple strategies support coming soon.
        /// </summary>
        /// <value>Array detailing sender strategies. Must contain exactly 1 element. Multiple strategies support coming soon.</value>
        [JsonPropertyName("default_sender_strategies")]
        public List<CreateDefaultSenderRequestDefaultSenderStrategiesInner> DefaultSenderStrategies { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateDefaultSenderRequest {\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  ProductType: ").Append(ProductType).Append("\n");
            sb.Append("  DefaultSenderStrategies: ").Append(DefaultSenderStrategies).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateDefaultSenderRequest" />
    /// </summary>
    public class CreateDefaultSenderRequestJsonConverter : JsonConverter<CreateDefaultSenderRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateDefaultSenderRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateDefaultSenderRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> countryCode = default;
            Option<CreateDefaultSenderRequest.ProductTypeEnum?> productType = default;
            Option<List<CreateDefaultSenderRequestDefaultSenderStrategiesInner>?> defaultSenderStrategies = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "country_code":
                            countryCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "product_type":
                            string? productTypeRawValue = utf8JsonReader.GetString();
                            if (productTypeRawValue != null)
                                productType = new Option<CreateDefaultSenderRequest.ProductTypeEnum?>(CreateDefaultSenderRequest.ProductTypeEnumFromStringOrDefault(productTypeRawValue));
                            break;
                        case "default_sender_strategies":
                            defaultSenderStrategies = new Option<List<CreateDefaultSenderRequestDefaultSenderStrategiesInner>?>(JsonSerializer.Deserialize<List<CreateDefaultSenderRequestDefaultSenderStrategiesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!countryCode.IsSet)
                throw new ArgumentException("Property is required for class CreateDefaultSenderRequest.", nameof(countryCode));

            if (!productType.IsSet)
                throw new ArgumentException("Property is required for class CreateDefaultSenderRequest.", nameof(productType));

            if (!defaultSenderStrategies.IsSet)
                throw new ArgumentException("Property is required for class CreateDefaultSenderRequest.", nameof(defaultSenderStrategies));

            if (countryCode.IsSet && countryCode.Value == null)
                throw new ArgumentNullException(nameof(countryCode), "Property is not nullable for class CreateDefaultSenderRequest.");

            if (productType.IsSet && productType.Value == null)
                throw new ArgumentNullException(nameof(productType), "Property is not nullable for class CreateDefaultSenderRequest.");

            if (defaultSenderStrategies.IsSet && defaultSenderStrategies.Value == null)
                throw new ArgumentNullException(nameof(defaultSenderStrategies), "Property is not nullable for class CreateDefaultSenderRequest.");

            return new CreateDefaultSenderRequest(countryCode.Value!, productType.Value!.Value!, defaultSenderStrategies.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CreateDefaultSenderRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createDefaultSenderRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateDefaultSenderRequest createDefaultSenderRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createDefaultSenderRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateDefaultSenderRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createDefaultSenderRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateDefaultSenderRequest createDefaultSenderRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createDefaultSenderRequest.CountryCode == null)
                throw new ArgumentNullException(nameof(createDefaultSenderRequest.CountryCode), "Property is required for class CreateDefaultSenderRequest.");

            if (createDefaultSenderRequest.DefaultSenderStrategies == null)
                throw new ArgumentNullException(nameof(createDefaultSenderRequest.DefaultSenderStrategies), "Property is required for class CreateDefaultSenderRequest.");

            writer.WriteString("country_code", createDefaultSenderRequest.CountryCode);

            var productTypeRawValue = CreateDefaultSenderRequest.ProductTypeEnumToJsonValue(createDefaultSenderRequest.ProductType);
            writer.WriteString("product_type", productTypeRawValue);
            writer.WritePropertyName("default_sender_strategies");
            JsonSerializer.Serialize(writer, createDefaultSenderRequest.DefaultSenderStrategies, jsonSerializerOptions);
        }
    }
}
