// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// CreateResellerAccountRequest
    /// </summary>
    public partial class CreateResellerAccountRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateResellerAccountRequest" /> class.
        /// </summary>
        /// <param name="country">country</param>
        /// <param name="password">password</param>
        /// <param name="userEmail">userEmail</param>
        /// <param name="userFirstName">userFirstName</param>
        /// <param name="userLastName">userLastName</param>
        /// <param name="accountName">accountName</param>
        /// <param name="userPhone">userPhone</param>
        /// <param name="username">username</param>
        [JsonConstructor]
        public CreateResellerAccountRequest(Option<string?> country = default, Option<string?> password = default, Option<string?> userEmail = default, Option<string?> userFirstName = default, Option<string?> userLastName = default, Option<string?> accountName = default, Option<string?> userPhone = default, Option<string?> username = default)
        {
            CountryOption = country;
            PasswordOption = password;
            UserEmailOption = userEmail;
            UserFirstNameOption = userFirstName;
            UserLastNameOption = userLastName;
            AccountNameOption = accountName;
            UserPhoneOption = userPhone;
            UsernameOption = username;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Country
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [JsonPropertyName("country")]
        public string? Country { get { return this.CountryOption.Value; } set { this.CountryOption = new(value); } }

        /// <summary>
        /// Used to track the state of Password
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PasswordOption { get; private set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [JsonPropertyName("password")]
        public string? Password { get { return this.PasswordOption.Value; } set { this.PasswordOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserEmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserEmail
        /// </summary>
        [JsonPropertyName("user_email")]
        public string? UserEmail { get { return this.UserEmailOption.Value; } set { this.UserEmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserFirstName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserFirstNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserFirstName
        /// </summary>
        [JsonPropertyName("user_first_name")]
        public string? UserFirstName { get { return this.UserFirstNameOption.Value; } set { this.UserFirstNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserLastName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserLastNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserLastName
        /// </summary>
        [JsonPropertyName("user_last_name")]
        public string? UserLastName { get { return this.UserLastNameOption.Value; } set { this.UserLastNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of AccountName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AccountNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets AccountName
        /// </summary>
        [JsonPropertyName("account_name")]
        public string? AccountName { get { return this.AccountNameOption.Value; } set { this.AccountNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserPhone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserPhoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserPhone
        /// </summary>
        [JsonPropertyName("user_phone")]
        public string? UserPhone { get { return this.UserPhoneOption.Value; } set { this.UserPhoneOption = new(value); } }

        /// <summary>
        /// Used to track the state of Username
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UsernameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [JsonPropertyName("username")]
        public string? Username { get { return this.UsernameOption.Value; } set { this.UsernameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateResellerAccountRequest {\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  UserEmail: ").Append(UserEmail).Append("\n");
            sb.Append("  UserFirstName: ").Append(UserFirstName).Append("\n");
            sb.Append("  UserLastName: ").Append(UserLastName).Append("\n");
            sb.Append("  AccountName: ").Append(AccountName).Append("\n");
            sb.Append("  UserPhone: ").Append(UserPhone).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateResellerAccountRequest" />
    /// </summary>
    public class CreateResellerAccountRequestJsonConverter : JsonConverter<CreateResellerAccountRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateResellerAccountRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateResellerAccountRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> country = default;
            Option<string?> password = default;
            Option<string?> userEmail = default;
            Option<string?> userFirstName = default;
            Option<string?> userLastName = default;
            Option<string?> accountName = default;
            Option<string?> userPhone = default;
            Option<string?> username = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "country":
                            country = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "password":
                            password = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_email":
                            userEmail = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_first_name":
                            userFirstName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_last_name":
                            userLastName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "account_name":
                            accountName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_phone":
                            userPhone = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "username":
                            username = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (country.IsSet && country.Value == null)
                throw new ArgumentNullException(nameof(country), "Property is not nullable for class CreateResellerAccountRequest.");

            if (password.IsSet && password.Value == null)
                throw new ArgumentNullException(nameof(password), "Property is not nullable for class CreateResellerAccountRequest.");

            if (userEmail.IsSet && userEmail.Value == null)
                throw new ArgumentNullException(nameof(userEmail), "Property is not nullable for class CreateResellerAccountRequest.");

            if (userFirstName.IsSet && userFirstName.Value == null)
                throw new ArgumentNullException(nameof(userFirstName), "Property is not nullable for class CreateResellerAccountRequest.");

            if (userLastName.IsSet && userLastName.Value == null)
                throw new ArgumentNullException(nameof(userLastName), "Property is not nullable for class CreateResellerAccountRequest.");

            if (accountName.IsSet && accountName.Value == null)
                throw new ArgumentNullException(nameof(accountName), "Property is not nullable for class CreateResellerAccountRequest.");

            if (userPhone.IsSet && userPhone.Value == null)
                throw new ArgumentNullException(nameof(userPhone), "Property is not nullable for class CreateResellerAccountRequest.");

            if (username.IsSet && username.Value == null)
                throw new ArgumentNullException(nameof(username), "Property is not nullable for class CreateResellerAccountRequest.");

            return new CreateResellerAccountRequest(country, password, userEmail, userFirstName, userLastName, accountName, userPhone, username);
        }

        /// <summary>
        /// Serializes a <see cref="CreateResellerAccountRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createResellerAccountRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateResellerAccountRequest createResellerAccountRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createResellerAccountRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateResellerAccountRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createResellerAccountRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateResellerAccountRequest createResellerAccountRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createResellerAccountRequest.CountryOption.IsSet && createResellerAccountRequest.Country == null)
                throw new ArgumentNullException(nameof(createResellerAccountRequest.Country), "Property is required for class CreateResellerAccountRequest.");

            if (createResellerAccountRequest.PasswordOption.IsSet && createResellerAccountRequest.Password == null)
                throw new ArgumentNullException(nameof(createResellerAccountRequest.Password), "Property is required for class CreateResellerAccountRequest.");

            if (createResellerAccountRequest.UserEmailOption.IsSet && createResellerAccountRequest.UserEmail == null)
                throw new ArgumentNullException(nameof(createResellerAccountRequest.UserEmail), "Property is required for class CreateResellerAccountRequest.");

            if (createResellerAccountRequest.UserFirstNameOption.IsSet && createResellerAccountRequest.UserFirstName == null)
                throw new ArgumentNullException(nameof(createResellerAccountRequest.UserFirstName), "Property is required for class CreateResellerAccountRequest.");

            if (createResellerAccountRequest.UserLastNameOption.IsSet && createResellerAccountRequest.UserLastName == null)
                throw new ArgumentNullException(nameof(createResellerAccountRequest.UserLastName), "Property is required for class CreateResellerAccountRequest.");

            if (createResellerAccountRequest.AccountNameOption.IsSet && createResellerAccountRequest.AccountName == null)
                throw new ArgumentNullException(nameof(createResellerAccountRequest.AccountName), "Property is required for class CreateResellerAccountRequest.");

            if (createResellerAccountRequest.UserPhoneOption.IsSet && createResellerAccountRequest.UserPhone == null)
                throw new ArgumentNullException(nameof(createResellerAccountRequest.UserPhone), "Property is required for class CreateResellerAccountRequest.");

            if (createResellerAccountRequest.UsernameOption.IsSet && createResellerAccountRequest.Username == null)
                throw new ArgumentNullException(nameof(createResellerAccountRequest.Username), "Property is required for class CreateResellerAccountRequest.");

            if (createResellerAccountRequest.CountryOption.IsSet)
                writer.WriteString("country", createResellerAccountRequest.Country);

            if (createResellerAccountRequest.PasswordOption.IsSet)
                writer.WriteString("password", createResellerAccountRequest.Password);

            if (createResellerAccountRequest.UserEmailOption.IsSet)
                writer.WriteString("user_email", createResellerAccountRequest.UserEmail);

            if (createResellerAccountRequest.UserFirstNameOption.IsSet)
                writer.WriteString("user_first_name", createResellerAccountRequest.UserFirstName);

            if (createResellerAccountRequest.UserLastNameOption.IsSet)
                writer.WriteString("user_last_name", createResellerAccountRequest.UserLastName);

            if (createResellerAccountRequest.AccountNameOption.IsSet)
                writer.WriteString("account_name", createResellerAccountRequest.AccountName);

            if (createResellerAccountRequest.UserPhoneOption.IsSet)
                writer.WriteString("user_phone", createResellerAccountRequest.UserPhone);

            if (createResellerAccountRequest.UsernameOption.IsSet)
                writer.WriteString("username", createResellerAccountRequest.Username);
        }
    }
}
