// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// CreateDeliveryIssueRequest
    /// </summary>
    public partial class CreateDeliveryIssueRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDeliveryIssueRequest" /> class.
        /// </summary>
        /// <param name="messageId">messageId</param>
        /// <param name="type">type</param>
        /// <param name="description">description</param>
        /// <param name="emailAddress">emailAddress</param>
        /// <param name="clientComments">clientComments</param>
        /// <param name="supportComments">supportComments</param>
        /// <param name="resolved">resolved</param>
        [JsonConstructor]
        public CreateDeliveryIssueRequest(Option<string?> messageId = default, Option<string?> type = default, Option<string?> description = default, Option<string?> emailAddress = default, Option<string?> clientComments = default, Option<string?> supportComments = default, Option<bool?> resolved = default)
        {
            MessageIdOption = messageId;
            TypeOption = type;
            DescriptionOption = description;
            EmailAddressOption = emailAddress;
            ClientCommentsOption = clientComments;
            SupportCommentsOption = supportComments;
            ResolvedOption = resolved;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of MessageId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets MessageId
        /// </summary>
        [JsonPropertyName("message_id")]
        public string? MessageId { get { return this.MessageIdOption.Value; } set { this.MessageIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get { return this.TypeOption.Value; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of EmailAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmailAddress
        /// </summary>
        [JsonPropertyName("email_address")]
        public string? EmailAddress { get { return this.EmailAddressOption.Value; } set { this.EmailAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClientComments
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClientCommentsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ClientComments
        /// </summary>
        [JsonPropertyName("client_comments")]
        public string? ClientComments { get { return this.ClientCommentsOption.Value; } set { this.ClientCommentsOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportComments
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SupportCommentsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportComments
        /// </summary>
        [JsonPropertyName("support_comments")]
        public string? SupportComments { get { return this.SupportCommentsOption.Value; } set { this.SupportCommentsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Resolved
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ResolvedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Resolved
        /// </summary>
        [JsonPropertyName("resolved")]
        public bool? Resolved { get { return this.ResolvedOption.Value; } set { this.ResolvedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateDeliveryIssueRequest {\n");
            sb.Append("  MessageId: ").Append(MessageId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  EmailAddress: ").Append(EmailAddress).Append("\n");
            sb.Append("  ClientComments: ").Append(ClientComments).Append("\n");
            sb.Append("  SupportComments: ").Append(SupportComments).Append("\n");
            sb.Append("  Resolved: ").Append(Resolved).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateDeliveryIssueRequest" />
    /// </summary>
    public class CreateDeliveryIssueRequestJsonConverter : JsonConverter<CreateDeliveryIssueRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateDeliveryIssueRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateDeliveryIssueRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> messageId = default;
            Option<string?> type = default;
            Option<string?> description = default;
            Option<string?> emailAddress = default;
            Option<string?> clientComments = default;
            Option<string?> supportComments = default;
            Option<bool?> resolved = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "message_id":
                            messageId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email_address":
                            emailAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "client_comments":
                            clientComments = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "support_comments":
                            supportComments = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resolved":
                            resolved = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (messageId.IsSet && messageId.Value == null)
                throw new ArgumentNullException(nameof(messageId), "Property is not nullable for class CreateDeliveryIssueRequest.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class CreateDeliveryIssueRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class CreateDeliveryIssueRequest.");

            if (emailAddress.IsSet && emailAddress.Value == null)
                throw new ArgumentNullException(nameof(emailAddress), "Property is not nullable for class CreateDeliveryIssueRequest.");

            if (clientComments.IsSet && clientComments.Value == null)
                throw new ArgumentNullException(nameof(clientComments), "Property is not nullable for class CreateDeliveryIssueRequest.");

            if (supportComments.IsSet && supportComments.Value == null)
                throw new ArgumentNullException(nameof(supportComments), "Property is not nullable for class CreateDeliveryIssueRequest.");

            if (resolved.IsSet && resolved.Value == null)
                throw new ArgumentNullException(nameof(resolved), "Property is not nullable for class CreateDeliveryIssueRequest.");

            return new CreateDeliveryIssueRequest(messageId, type, description, emailAddress, clientComments, supportComments, resolved);
        }

        /// <summary>
        /// Serializes a <see cref="CreateDeliveryIssueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createDeliveryIssueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateDeliveryIssueRequest createDeliveryIssueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createDeliveryIssueRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateDeliveryIssueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createDeliveryIssueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateDeliveryIssueRequest createDeliveryIssueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createDeliveryIssueRequest.MessageIdOption.IsSet && createDeliveryIssueRequest.MessageId == null)
                throw new ArgumentNullException(nameof(createDeliveryIssueRequest.MessageId), "Property is required for class CreateDeliveryIssueRequest.");

            if (createDeliveryIssueRequest.TypeOption.IsSet && createDeliveryIssueRequest.Type == null)
                throw new ArgumentNullException(nameof(createDeliveryIssueRequest.Type), "Property is required for class CreateDeliveryIssueRequest.");

            if (createDeliveryIssueRequest.DescriptionOption.IsSet && createDeliveryIssueRequest.Description == null)
                throw new ArgumentNullException(nameof(createDeliveryIssueRequest.Description), "Property is required for class CreateDeliveryIssueRequest.");

            if (createDeliveryIssueRequest.EmailAddressOption.IsSet && createDeliveryIssueRequest.EmailAddress == null)
                throw new ArgumentNullException(nameof(createDeliveryIssueRequest.EmailAddress), "Property is required for class CreateDeliveryIssueRequest.");

            if (createDeliveryIssueRequest.ClientCommentsOption.IsSet && createDeliveryIssueRequest.ClientComments == null)
                throw new ArgumentNullException(nameof(createDeliveryIssueRequest.ClientComments), "Property is required for class CreateDeliveryIssueRequest.");

            if (createDeliveryIssueRequest.SupportCommentsOption.IsSet && createDeliveryIssueRequest.SupportComments == null)
                throw new ArgumentNullException(nameof(createDeliveryIssueRequest.SupportComments), "Property is required for class CreateDeliveryIssueRequest.");

            if (createDeliveryIssueRequest.MessageIdOption.IsSet)
                writer.WriteString("message_id", createDeliveryIssueRequest.MessageId);

            if (createDeliveryIssueRequest.TypeOption.IsSet)
                writer.WriteString("type", createDeliveryIssueRequest.Type);

            if (createDeliveryIssueRequest.DescriptionOption.IsSet)
                writer.WriteString("description", createDeliveryIssueRequest.Description);

            if (createDeliveryIssueRequest.EmailAddressOption.IsSet)
                writer.WriteString("email_address", createDeliveryIssueRequest.EmailAddress);

            if (createDeliveryIssueRequest.ClientCommentsOption.IsSet)
                writer.WriteString("client_comments", createDeliveryIssueRequest.ClientComments);

            if (createDeliveryIssueRequest.SupportCommentsOption.IsSet)
                writer.WriteString("support_comments", createDeliveryIssueRequest.SupportComments);

            if (createDeliveryIssueRequest.ResolvedOption.IsSet)
                writer.WriteBoolean("resolved", createDeliveryIssueRequest.ResolvedOption.Value!.Value);
        }
    }
}
