// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// CreateTestInboundSmsRequest
    /// </summary>
    public partial class CreateTestInboundSmsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTestInboundSmsRequest" /> class.
        /// </summary>
        /// <param name="url">The webhook URL where the inbound SMS will be sent to.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;You can create a webhook URL in &lt;em&gt;Pipedream&lt;/em&gt; to test receiving the inbound SMS. Follow the instructions &lt;a href&#x3D;\&quot;https://help.clicksend.com/en/articles/43703-integration-guide-pipedream\&quot; target&#x3D;\&quot;_blank\&quot;&gt;here.&lt;/a&gt;&lt;/p&gt; &lt;/div&gt;  </param>
        /// <param name="webhookType">Specifies the HTTP method used when the webhook sends a request to the URL. The available options are:  - **post** (Default): Sends the event data using an HTTP POST request.      - **get**: Sends the event data as query parameters in an HTTP GET request.      - **json**: Sends the event data using a custom JSON format (via a POST request).      This parameter is used to determine how the data will be transmitted, depending on your preferred method and how the receiving system is designed to process incoming requests.</param>
        [JsonConstructor]
        public CreateTestInboundSmsRequest(string url, Option<string?> webhookType = default)
        {
            Url = url;
            WebhookTypeOption = webhookType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The webhook URL where the inbound SMS will be sent to.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;You can create a webhook URL in &lt;em&gt;Pipedream&lt;/em&gt; to test receiving the inbound SMS. Follow the instructions &lt;a href&#x3D;\&quot;https://help.clicksend.com/en/articles/43703-integration-guide-pipedream\&quot; target&#x3D;\&quot;_blank\&quot;&gt;here.&lt;/a&gt;&lt;/p&gt; &lt;/div&gt;  
        /// </summary>
        /// <value>The webhook URL where the inbound SMS will be sent to.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;You can create a webhook URL in &lt;em&gt;Pipedream&lt;/em&gt; to test receiving the inbound SMS. Follow the instructions &lt;a href&#x3D;\&quot;https://help.clicksend.com/en/articles/43703-integration-guide-pipedream\&quot; target&#x3D;\&quot;_blank\&quot;&gt;here.&lt;/a&gt;&lt;/p&gt; &lt;/div&gt;  </value>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Used to track the state of WebhookType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WebhookTypeOption { get; private set; }

        /// <summary>
        /// Specifies the HTTP method used when the webhook sends a request to the URL. The available options are:  - **post** (Default): Sends the event data using an HTTP POST request.      - **get**: Sends the event data as query parameters in an HTTP GET request.      - **json**: Sends the event data using a custom JSON format (via a POST request).      This parameter is used to determine how the data will be transmitted, depending on your preferred method and how the receiving system is designed to process incoming requests.
        /// </summary>
        /// <value>Specifies the HTTP method used when the webhook sends a request to the URL. The available options are:  - **post** (Default): Sends the event data using an HTTP POST request.      - **get**: Sends the event data as query parameters in an HTTP GET request.      - **json**: Sends the event data using a custom JSON format (via a POST request).      This parameter is used to determine how the data will be transmitted, depending on your preferred method and how the receiving system is designed to process incoming requests.</value>
        [JsonPropertyName("webhook_type")]
        public string? WebhookType { get { return this.WebhookTypeOption.Value; } set { this.WebhookTypeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateTestInboundSmsRequest {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  WebhookType: ").Append(WebhookType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateTestInboundSmsRequest" />
    /// </summary>
    public class CreateTestInboundSmsRequestJsonConverter : JsonConverter<CreateTestInboundSmsRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateTestInboundSmsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateTestInboundSmsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<string?> webhookType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "webhook_type":
                            webhookType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class CreateTestInboundSmsRequest.", nameof(url));

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class CreateTestInboundSmsRequest.");

            if (webhookType.IsSet && webhookType.Value == null)
                throw new ArgumentNullException(nameof(webhookType), "Property is not nullable for class CreateTestInboundSmsRequest.");

            return new CreateTestInboundSmsRequest(url.Value!, webhookType);
        }

        /// <summary>
        /// Serializes a <see cref="CreateTestInboundSmsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createTestInboundSmsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateTestInboundSmsRequest createTestInboundSmsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createTestInboundSmsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateTestInboundSmsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createTestInboundSmsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateTestInboundSmsRequest createTestInboundSmsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createTestInboundSmsRequest.Url == null)
                throw new ArgumentNullException(nameof(createTestInboundSmsRequest.Url), "Property is required for class CreateTestInboundSmsRequest.");

            if (createTestInboundSmsRequest.WebhookTypeOption.IsSet && createTestInboundSmsRequest.WebhookType == null)
                throw new ArgumentNullException(nameof(createTestInboundSmsRequest.WebhookType), "Property is required for class CreateTestInboundSmsRequest.");

            writer.WriteString("url", createTestInboundSmsRequest.Url);

            if (createTestInboundSmsRequest.WebhookTypeOption.IsSet)
                writer.WriteString("webhook_type", createTestInboundSmsRequest.WebhookType);
        }
    }
}
