// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// EmailDeliveryReceiptRule
    /// </summary>
    public partial class EmailDeliveryReceiptRule : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailDeliveryReceiptRule" /> class.
        /// </summary>
        /// <param name="receiptRuleId">The ID of the receipt rule.</param>
        /// <param name="ruleName">The name of the receipt rule.</param>
        /// <param name="matchType">The type of match for the rule.</param>
        /// <param name="action">The action to be taken by the rule.</param>
        /// <param name="actionAddress">The address associated with the action.</param>
        /// <param name="enabled">Indicates whether the rule is enabled.</param>
        [JsonConstructor]
        public EmailDeliveryReceiptRule(Option<int?> receiptRuleId = default, Option<string?> ruleName = default, Option<int?> matchType = default, Option<string?> action = default, Option<string?> actionAddress = default, Option<int?> enabled = default)
        {
            ReceiptRuleIdOption = receiptRuleId;
            RuleNameOption = ruleName;
            MatchTypeOption = matchType;
            ActionOption = action;
            ActionAddressOption = actionAddress;
            EnabledOption = enabled;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ReceiptRuleId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ReceiptRuleIdOption { get; private set; }

        /// <summary>
        /// The ID of the receipt rule.
        /// </summary>
        /// <value>The ID of the receipt rule.</value>
        /* <example>1</example> */
        [JsonPropertyName("receipt_rule_id")]
        public int? ReceiptRuleId { get { return this.ReceiptRuleIdOption.Value; } set { this.ReceiptRuleIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of RuleName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RuleNameOption { get; private set; }

        /// <summary>
        /// The name of the receipt rule.
        /// </summary>
        /// <value>The name of the receipt rule.</value>
        /* <example>Email Test Rule</example> */
        [JsonPropertyName("rule_name")]
        public string? RuleName { get { return this.RuleNameOption.Value; } set { this.RuleNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of MatchType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MatchTypeOption { get; private set; }

        /// <summary>
        /// The type of match for the rule.
        /// </summary>
        /// <value>The type of match for the rule.</value>
        /* <example>0</example> */
        [JsonPropertyName("match_type")]
        public int? MatchType { get { return this.MatchTypeOption.Value; } set { this.MatchTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Action
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActionOption { get; private set; }

        /// <summary>
        /// The action to be taken by the rule.
        /// </summary>
        /// <value>The action to be taken by the rule.</value>
        /* <example>URL</example> */
        [JsonPropertyName("action")]
        public string? Action { get { return this.ActionOption.Value; } set { this.ActionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ActionAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActionAddressOption { get; private set; }

        /// <summary>
        /// The address associated with the action.
        /// </summary>
        /// <value>The address associated with the action.</value>
        /* <example>http://yourdomain.com</example> */
        [JsonPropertyName("action_address")]
        public string? ActionAddress { get { return this.ActionAddressOption.Value; } set { this.ActionAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EnabledOption { get; private set; }

        /// <summary>
        /// Indicates whether the rule is enabled.
        /// </summary>
        /// <value>Indicates whether the rule is enabled.</value>
        /* <example>1</example> */
        [JsonPropertyName("enabled")]
        public int? Enabled { get { return this.EnabledOption.Value; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailDeliveryReceiptRule {\n");
            sb.Append("  ReceiptRuleId: ").Append(ReceiptRuleId).Append("\n");
            sb.Append("  RuleName: ").Append(RuleName).Append("\n");
            sb.Append("  MatchType: ").Append(MatchType).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  ActionAddress: ").Append(ActionAddress).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EmailDeliveryReceiptRule" />
    /// </summary>
    public class EmailDeliveryReceiptRuleJsonConverter : JsonConverter<EmailDeliveryReceiptRule>
    {
        /// <summary>
        /// Deserializes json to <see cref="EmailDeliveryReceiptRule" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EmailDeliveryReceiptRule Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> receiptRuleId = default;
            Option<string?> ruleName = default;
            Option<int?> matchType = default;
            Option<string?> action = default;
            Option<string?> actionAddress = default;
            Option<int?> enabled = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "receipt_rule_id":
                            receiptRuleId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "rule_name":
                            ruleName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "match_type":
                            matchType = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "action":
                            action = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action_address":
                            actionAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "enabled":
                            enabled = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (receiptRuleId.IsSet && receiptRuleId.Value == null)
                throw new ArgumentNullException(nameof(receiptRuleId), "Property is not nullable for class EmailDeliveryReceiptRule.");

            if (ruleName.IsSet && ruleName.Value == null)
                throw new ArgumentNullException(nameof(ruleName), "Property is not nullable for class EmailDeliveryReceiptRule.");

            if (matchType.IsSet && matchType.Value == null)
                throw new ArgumentNullException(nameof(matchType), "Property is not nullable for class EmailDeliveryReceiptRule.");

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class EmailDeliveryReceiptRule.");

            if (actionAddress.IsSet && actionAddress.Value == null)
                throw new ArgumentNullException(nameof(actionAddress), "Property is not nullable for class EmailDeliveryReceiptRule.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class EmailDeliveryReceiptRule.");

            return new EmailDeliveryReceiptRule(receiptRuleId, ruleName, matchType, action, actionAddress, enabled);
        }

        /// <summary>
        /// Serializes a <see cref="EmailDeliveryReceiptRule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailDeliveryReceiptRule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EmailDeliveryReceiptRule emailDeliveryReceiptRule, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, emailDeliveryReceiptRule, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EmailDeliveryReceiptRule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailDeliveryReceiptRule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EmailDeliveryReceiptRule emailDeliveryReceiptRule, JsonSerializerOptions jsonSerializerOptions)
        {
            if (emailDeliveryReceiptRule.RuleNameOption.IsSet && emailDeliveryReceiptRule.RuleName == null)
                throw new ArgumentNullException(nameof(emailDeliveryReceiptRule.RuleName), "Property is required for class EmailDeliveryReceiptRule.");

            if (emailDeliveryReceiptRule.ActionOption.IsSet && emailDeliveryReceiptRule.Action == null)
                throw new ArgumentNullException(nameof(emailDeliveryReceiptRule.Action), "Property is required for class EmailDeliveryReceiptRule.");

            if (emailDeliveryReceiptRule.ActionAddressOption.IsSet && emailDeliveryReceiptRule.ActionAddress == null)
                throw new ArgumentNullException(nameof(emailDeliveryReceiptRule.ActionAddress), "Property is required for class EmailDeliveryReceiptRule.");

            if (emailDeliveryReceiptRule.ReceiptRuleIdOption.IsSet)
                writer.WriteNumber("receipt_rule_id", emailDeliveryReceiptRule.ReceiptRuleIdOption.Value!.Value);

            if (emailDeliveryReceiptRule.RuleNameOption.IsSet)
                writer.WriteString("rule_name", emailDeliveryReceiptRule.RuleName);

            if (emailDeliveryReceiptRule.MatchTypeOption.IsSet)
                writer.WriteNumber("match_type", emailDeliveryReceiptRule.MatchTypeOption.Value!.Value);

            if (emailDeliveryReceiptRule.ActionOption.IsSet)
                writer.WriteString("action", emailDeliveryReceiptRule.Action);

            if (emailDeliveryReceiptRule.ActionAddressOption.IsSet)
                writer.WriteString("action_address", emailDeliveryReceiptRule.ActionAddress);

            if (emailDeliveryReceiptRule.EnabledOption.IsSet)
                writer.WriteNumber("enabled", emailDeliveryReceiptRule.EnabledOption.Value!.Value);
        }
    }
}
