// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// EmailCampaign
    /// </summary>
    public partial class EmailCampaign : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailCampaign" /> class.
        /// </summary>
        /// <param name="emailCampaignId">The ID of the email campaign.</param>
        /// <param name="name">The name of the email campaign.</param>
        /// <param name="userId">The ID of the user who created the email campaign.</param>
        /// <param name="subaccountId">The ID of the subaccount associated with the email campaign.</param>
        /// <param name="subject">The subject of the email campaign.</param>
        /// <param name="listId">The ID of the email list associated with the campaign.</param>
        /// <param name="fromEmailAddressId">The ID of the sender&#39;s email address.</param>
        /// <param name="fromName">The name of the sender.</param>
        /// <param name="templateId">The ID of the email template used in the campaign.</param>
        /// <param name="schedule">The schedule for sending the email campaign.</param>
        /// <param name="status">The status of the email campaign (e.g., Sent, Scheduled, Draft).</param>
        /// <param name="dateAdded">The date when the email campaign was added.</param>
        /// <param name="customString">A custom string associated with the email campaign.</param>
        /// <param name="sendCount">The count of emails sent in the campaign.</param>
        /// <param name="openCount">The count of emails opened in the campaign.</param>
        /// <param name="clickCount">The count of links clicked in the campaign.</param>
        /// <param name="hardBounceCount">The count of hard bounces in the campaign.</param>
        /// <param name="softBounceCount">The count of soft bounces in the campaign.</param>
        /// <param name="abuseCount">The count of abuse complaints in the campaign.</param>
        /// <param name="unsubscribeCount">The count of unsubscribes in the campaign.</param>
        /// <param name="body">The body of the email campaign.</param>
        /// <param name="bodyPlainText">The plain text body of the email campaign.</param>
        [JsonConstructor]
        public EmailCampaign(Option<int?> emailCampaignId = default, Option<string?> name = default, Option<int?> userId = default, Option<int?> subaccountId = default, Option<string?> subject = default, Option<int?> listId = default, Option<int?> fromEmailAddressId = default, Option<string?> fromName = default, Option<int?> templateId = default, Option<string?> schedule = default, Option<string?> status = default, Option<string?> dateAdded = default, Option<string?> customString = default, Option<int?> sendCount = default, Option<int?> openCount = default, Option<int?> clickCount = default, Option<int?> hardBounceCount = default, Option<int?> softBounceCount = default, Option<int?> abuseCount = default, Option<int?> unsubscribeCount = default, Option<string?> body = default, Option<string?> bodyPlainText = default)
        {
            EmailCampaignIdOption = emailCampaignId;
            NameOption = name;
            UserIdOption = userId;
            SubaccountIdOption = subaccountId;
            SubjectOption = subject;
            ListIdOption = listId;
            FromEmailAddressIdOption = fromEmailAddressId;
            FromNameOption = fromName;
            TemplateIdOption = templateId;
            ScheduleOption = schedule;
            StatusOption = status;
            DateAddedOption = dateAdded;
            CustomStringOption = customString;
            SendCountOption = sendCount;
            OpenCountOption = openCount;
            ClickCountOption = clickCount;
            HardBounceCountOption = hardBounceCount;
            SoftBounceCountOption = softBounceCount;
            AbuseCountOption = abuseCount;
            UnsubscribeCountOption = unsubscribeCount;
            BodyOption = body;
            BodyPlainTextOption = bodyPlainText;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of EmailCampaignId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EmailCampaignIdOption { get; private set; }

        /// <summary>
        /// The ID of the email campaign.
        /// </summary>
        /// <value>The ID of the email campaign.</value>
        /* <example>64</example> */
        [JsonPropertyName("email_campaign_id")]
        public int? EmailCampaignId { get { return this.EmailCampaignIdOption.Value; } set { this.EmailCampaignIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// The name of the email campaign.
        /// </summary>
        /// <value>The name of the email campaign.</value>
        /* <example>test email</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> UserIdOption { get; private set; }

        /// <summary>
        /// The ID of the user who created the email campaign.
        /// </summary>
        /// <value>The ID of the user who created the email campaign.</value>
        /* <example>1201</example> */
        [JsonPropertyName("user_id")]
        public int? UserId { get { return this.UserIdOption.Value; } set { this.UserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SubaccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SubaccountIdOption { get; private set; }

        /// <summary>
        /// The ID of the subaccount associated with the email campaign.
        /// </summary>
        /// <value>The ID of the subaccount associated with the email campaign.</value>
        /* <example>1038</example> */
        [JsonPropertyName("subaccount_id")]
        public int? SubaccountId { get { return this.SubaccountIdOption.Value; } set { this.SubaccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// The subject of the email campaign.
        /// </summary>
        /// <value>The subject of the email campaign.</value>
        /* <example>My test subject</example> */
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption.Value; } set { this.SubjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of ListId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ListIdOption { get; private set; }

        /// <summary>
        /// The ID of the email list associated with the campaign.
        /// </summary>
        /// <value>The ID of the email list associated with the campaign.</value>
        /* <example>443</example> */
        [JsonPropertyName("list_id")]
        public int? ListId { get { return this.ListIdOption.Value; } set { this.ListIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of FromEmailAddressId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FromEmailAddressIdOption { get; private set; }

        /// <summary>
        /// The ID of the sender&#39;s email address.
        /// </summary>
        /// <value>The ID of the sender&#39;s email address.</value>
        /* <example>2</example> */
        [JsonPropertyName("from_email_address_id")]
        public int? FromEmailAddressId { get { return this.FromEmailAddressIdOption.Value; } set { this.FromEmailAddressIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of FromName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FromNameOption { get; private set; }

        /// <summary>
        /// The name of the sender.
        /// </summary>
        /// <value>The name of the sender.</value>
        /* <example>Test name</example> */
        [JsonPropertyName("from_name")]
        public string? FromName { get { return this.FromNameOption.Value; } set { this.FromNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of TemplateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TemplateIdOption { get; private set; }

        /// <summary>
        /// The ID of the email template used in the campaign.
        /// </summary>
        /// <value>The ID of the email template used in the campaign.</value>
        /* <example>24</example> */
        [JsonPropertyName("template_id")]
        public int? TemplateId { get { return this.TemplateIdOption.Value; } set { this.TemplateIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Schedule
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ScheduleOption { get; private set; }

        /// <summary>
        /// The schedule for sending the email campaign.
        /// </summary>
        /// <value>The schedule for sending the email campaign.</value>
        [JsonPropertyName("schedule")]
        public string? Schedule { get { return this.ScheduleOption.Value; } set { this.ScheduleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// The status of the email campaign (e.g., Sent, Scheduled, Draft).
        /// </summary>
        /// <value>The status of the email campaign (e.g., Sent, Scheduled, Draft).</value>
        /* <example>Sent</example> */
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of DateAdded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DateAddedOption { get; private set; }

        /// <summary>
        /// The date when the email campaign was added.
        /// </summary>
        /// <value>The date when the email campaign was added.</value>
        /* <example>1455586793</example> */
        [JsonPropertyName("date_added")]
        public string? DateAdded { get { return this.DateAddedOption.Value; } set { this.DateAddedOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomString
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomStringOption { get; private set; }

        /// <summary>
        /// A custom string associated with the email campaign.
        /// </summary>
        /// <value>A custom string associated with the email campaign.</value>
        [JsonPropertyName("custom_string")]
        public string? CustomString { get { return this.CustomStringOption.Value; } set { this.CustomStringOption = new(value); } }

        /// <summary>
        /// Used to track the state of SendCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SendCountOption { get; private set; }

        /// <summary>
        /// The count of emails sent in the campaign.
        /// </summary>
        /// <value>The count of emails sent in the campaign.</value>
        /* <example>0</example> */
        [JsonPropertyName("send_count")]
        public int? SendCount { get { return this.SendCountOption.Value; } set { this.SendCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of OpenCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OpenCountOption { get; private set; }

        /// <summary>
        /// The count of emails opened in the campaign.
        /// </summary>
        /// <value>The count of emails opened in the campaign.</value>
        /* <example>5</example> */
        [JsonPropertyName("open_count")]
        public int? OpenCount { get { return this.OpenCountOption.Value; } set { this.OpenCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClickCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ClickCountOption { get; private set; }

        /// <summary>
        /// The count of links clicked in the campaign.
        /// </summary>
        /// <value>The count of links clicked in the campaign.</value>
        /* <example>0</example> */
        [JsonPropertyName("click_count")]
        public int? ClickCount { get { return this.ClickCountOption.Value; } set { this.ClickCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of HardBounceCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> HardBounceCountOption { get; private set; }

        /// <summary>
        /// The count of hard bounces in the campaign.
        /// </summary>
        /// <value>The count of hard bounces in the campaign.</value>
        /* <example>0</example> */
        [JsonPropertyName("hard_bounce_count")]
        public int? HardBounceCount { get { return this.HardBounceCountOption.Value; } set { this.HardBounceCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of SoftBounceCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SoftBounceCountOption { get; private set; }

        /// <summary>
        /// The count of soft bounces in the campaign.
        /// </summary>
        /// <value>The count of soft bounces in the campaign.</value>
        /* <example>0</example> */
        [JsonPropertyName("soft_bounce_count")]
        public int? SoftBounceCount { get { return this.SoftBounceCountOption.Value; } set { this.SoftBounceCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of AbuseCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> AbuseCountOption { get; private set; }

        /// <summary>
        /// The count of abuse complaints in the campaign.
        /// </summary>
        /// <value>The count of abuse complaints in the campaign.</value>
        /* <example>0</example> */
        [JsonPropertyName("abuse_count")]
        public int? AbuseCount { get { return this.AbuseCountOption.Value; } set { this.AbuseCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of UnsubscribeCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> UnsubscribeCountOption { get; private set; }

        /// <summary>
        /// The count of unsubscribes in the campaign.
        /// </summary>
        /// <value>The count of unsubscribes in the campaign.</value>
        /* <example>0</example> */
        [JsonPropertyName("unsubscribe_count")]
        public int? UnsubscribeCount { get { return this.UnsubscribeCountOption.Value; } set { this.UnsubscribeCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Body
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BodyOption { get; private set; }

        /// <summary>
        /// The body of the email campaign.
        /// </summary>
        /// <value>The body of the email campaign.</value>
        /* <example>test body</example> */
        [JsonPropertyName("body")]
        public string? Body { get { return this.BodyOption.Value; } set { this.BodyOption = new(value); } }

        /// <summary>
        /// Used to track the state of BodyPlainText
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BodyPlainTextOption { get; private set; }

        /// <summary>
        /// The plain text body of the email campaign.
        /// </summary>
        /// <value>The plain text body of the email campaign.</value>
        /* <example>test body</example> */
        [JsonPropertyName("body_plain_text")]
        public string? BodyPlainText { get { return this.BodyPlainTextOption.Value; } set { this.BodyPlainTextOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailCampaign {\n");
            sb.Append("  EmailCampaignId: ").Append(EmailCampaignId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  SubaccountId: ").Append(SubaccountId).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  ListId: ").Append(ListId).Append("\n");
            sb.Append("  FromEmailAddressId: ").Append(FromEmailAddressId).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  DateAdded: ").Append(DateAdded).Append("\n");
            sb.Append("  CustomString: ").Append(CustomString).Append("\n");
            sb.Append("  SendCount: ").Append(SendCount).Append("\n");
            sb.Append("  OpenCount: ").Append(OpenCount).Append("\n");
            sb.Append("  ClickCount: ").Append(ClickCount).Append("\n");
            sb.Append("  HardBounceCount: ").Append(HardBounceCount).Append("\n");
            sb.Append("  SoftBounceCount: ").Append(SoftBounceCount).Append("\n");
            sb.Append("  AbuseCount: ").Append(AbuseCount).Append("\n");
            sb.Append("  UnsubscribeCount: ").Append(UnsubscribeCount).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  BodyPlainText: ").Append(BodyPlainText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EmailCampaign" />
    /// </summary>
    public class EmailCampaignJsonConverter : JsonConverter<EmailCampaign>
    {
        /// <summary>
        /// Deserializes json to <see cref="EmailCampaign" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EmailCampaign Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> emailCampaignId = default;
            Option<string?> name = default;
            Option<int?> userId = default;
            Option<int?> subaccountId = default;
            Option<string?> subject = default;
            Option<int?> listId = default;
            Option<int?> fromEmailAddressId = default;
            Option<string?> fromName = default;
            Option<int?> templateId = default;
            Option<string?> schedule = default;
            Option<string?> status = default;
            Option<string?> dateAdded = default;
            Option<string?> customString = default;
            Option<int?> sendCount = default;
            Option<int?> openCount = default;
            Option<int?> clickCount = default;
            Option<int?> hardBounceCount = default;
            Option<int?> softBounceCount = default;
            Option<int?> abuseCount = default;
            Option<int?> unsubscribeCount = default;
            Option<string?> body = default;
            Option<string?> bodyPlainText = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email_campaign_id":
                            emailCampaignId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_id":
                            userId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "subaccount_id":
                            subaccountId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "list_id":
                            listId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "from_email_address_id":
                            fromEmailAddressId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "from_name":
                            fromName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "template_id":
                            templateId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "schedule":
                            schedule = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "date_added":
                            dateAdded = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "custom_string":
                            customString = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "send_count":
                            sendCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "open_count":
                            openCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "click_count":
                            clickCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "hard_bounce_count":
                            hardBounceCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "soft_bounce_count":
                            softBounceCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "abuse_count":
                            abuseCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "unsubscribe_count":
                            unsubscribeCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "body":
                            body = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "body_plain_text":
                            bodyPlainText = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (emailCampaignId.IsSet && emailCampaignId.Value == null)
                throw new ArgumentNullException(nameof(emailCampaignId), "Property is not nullable for class EmailCampaign.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class EmailCampaign.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class EmailCampaign.");

            if (subaccountId.IsSet && subaccountId.Value == null)
                throw new ArgumentNullException(nameof(subaccountId), "Property is not nullable for class EmailCampaign.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class EmailCampaign.");

            if (listId.IsSet && listId.Value == null)
                throw new ArgumentNullException(nameof(listId), "Property is not nullable for class EmailCampaign.");

            if (fromEmailAddressId.IsSet && fromEmailAddressId.Value == null)
                throw new ArgumentNullException(nameof(fromEmailAddressId), "Property is not nullable for class EmailCampaign.");

            if (fromName.IsSet && fromName.Value == null)
                throw new ArgumentNullException(nameof(fromName), "Property is not nullable for class EmailCampaign.");

            if (templateId.IsSet && templateId.Value == null)
                throw new ArgumentNullException(nameof(templateId), "Property is not nullable for class EmailCampaign.");

            if (schedule.IsSet && schedule.Value == null)
                throw new ArgumentNullException(nameof(schedule), "Property is not nullable for class EmailCampaign.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class EmailCampaign.");

            if (dateAdded.IsSet && dateAdded.Value == null)
                throw new ArgumentNullException(nameof(dateAdded), "Property is not nullable for class EmailCampaign.");

            if (customString.IsSet && customString.Value == null)
                throw new ArgumentNullException(nameof(customString), "Property is not nullable for class EmailCampaign.");

            if (sendCount.IsSet && sendCount.Value == null)
                throw new ArgumentNullException(nameof(sendCount), "Property is not nullable for class EmailCampaign.");

            if (openCount.IsSet && openCount.Value == null)
                throw new ArgumentNullException(nameof(openCount), "Property is not nullable for class EmailCampaign.");

            if (clickCount.IsSet && clickCount.Value == null)
                throw new ArgumentNullException(nameof(clickCount), "Property is not nullable for class EmailCampaign.");

            if (hardBounceCount.IsSet && hardBounceCount.Value == null)
                throw new ArgumentNullException(nameof(hardBounceCount), "Property is not nullable for class EmailCampaign.");

            if (softBounceCount.IsSet && softBounceCount.Value == null)
                throw new ArgumentNullException(nameof(softBounceCount), "Property is not nullable for class EmailCampaign.");

            if (abuseCount.IsSet && abuseCount.Value == null)
                throw new ArgumentNullException(nameof(abuseCount), "Property is not nullable for class EmailCampaign.");

            if (unsubscribeCount.IsSet && unsubscribeCount.Value == null)
                throw new ArgumentNullException(nameof(unsubscribeCount), "Property is not nullable for class EmailCampaign.");

            if (body.IsSet && body.Value == null)
                throw new ArgumentNullException(nameof(body), "Property is not nullable for class EmailCampaign.");

            if (bodyPlainText.IsSet && bodyPlainText.Value == null)
                throw new ArgumentNullException(nameof(bodyPlainText), "Property is not nullable for class EmailCampaign.");

            return new EmailCampaign(emailCampaignId, name, userId, subaccountId, subject, listId, fromEmailAddressId, fromName, templateId, schedule, status, dateAdded, customString, sendCount, openCount, clickCount, hardBounceCount, softBounceCount, abuseCount, unsubscribeCount, body, bodyPlainText);
        }

        /// <summary>
        /// Serializes a <see cref="EmailCampaign" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailCampaign"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EmailCampaign emailCampaign, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, emailCampaign, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EmailCampaign" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailCampaign"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EmailCampaign emailCampaign, JsonSerializerOptions jsonSerializerOptions)
        {
            if (emailCampaign.NameOption.IsSet && emailCampaign.Name == null)
                throw new ArgumentNullException(nameof(emailCampaign.Name), "Property is required for class EmailCampaign.");

            if (emailCampaign.SubjectOption.IsSet && emailCampaign.Subject == null)
                throw new ArgumentNullException(nameof(emailCampaign.Subject), "Property is required for class EmailCampaign.");

            if (emailCampaign.FromNameOption.IsSet && emailCampaign.FromName == null)
                throw new ArgumentNullException(nameof(emailCampaign.FromName), "Property is required for class EmailCampaign.");

            if (emailCampaign.ScheduleOption.IsSet && emailCampaign.Schedule == null)
                throw new ArgumentNullException(nameof(emailCampaign.Schedule), "Property is required for class EmailCampaign.");

            if (emailCampaign.StatusOption.IsSet && emailCampaign.Status == null)
                throw new ArgumentNullException(nameof(emailCampaign.Status), "Property is required for class EmailCampaign.");

            if (emailCampaign.DateAddedOption.IsSet && emailCampaign.DateAdded == null)
                throw new ArgumentNullException(nameof(emailCampaign.DateAdded), "Property is required for class EmailCampaign.");

            if (emailCampaign.CustomStringOption.IsSet && emailCampaign.CustomString == null)
                throw new ArgumentNullException(nameof(emailCampaign.CustomString), "Property is required for class EmailCampaign.");

            if (emailCampaign.BodyOption.IsSet && emailCampaign.Body == null)
                throw new ArgumentNullException(nameof(emailCampaign.Body), "Property is required for class EmailCampaign.");

            if (emailCampaign.BodyPlainTextOption.IsSet && emailCampaign.BodyPlainText == null)
                throw new ArgumentNullException(nameof(emailCampaign.BodyPlainText), "Property is required for class EmailCampaign.");

            if (emailCampaign.EmailCampaignIdOption.IsSet)
                writer.WriteNumber("email_campaign_id", emailCampaign.EmailCampaignIdOption.Value!.Value);

            if (emailCampaign.NameOption.IsSet)
                writer.WriteString("name", emailCampaign.Name);

            if (emailCampaign.UserIdOption.IsSet)
                writer.WriteNumber("user_id", emailCampaign.UserIdOption.Value!.Value);

            if (emailCampaign.SubaccountIdOption.IsSet)
                writer.WriteNumber("subaccount_id", emailCampaign.SubaccountIdOption.Value!.Value);

            if (emailCampaign.SubjectOption.IsSet)
                writer.WriteString("subject", emailCampaign.Subject);

            if (emailCampaign.ListIdOption.IsSet)
                writer.WriteNumber("list_id", emailCampaign.ListIdOption.Value!.Value);

            if (emailCampaign.FromEmailAddressIdOption.IsSet)
                writer.WriteNumber("from_email_address_id", emailCampaign.FromEmailAddressIdOption.Value!.Value);

            if (emailCampaign.FromNameOption.IsSet)
                writer.WriteString("from_name", emailCampaign.FromName);

            if (emailCampaign.TemplateIdOption.IsSet)
                writer.WriteNumber("template_id", emailCampaign.TemplateIdOption.Value!.Value);

            if (emailCampaign.ScheduleOption.IsSet)
                writer.WriteString("schedule", emailCampaign.Schedule);

            if (emailCampaign.StatusOption.IsSet)
                writer.WriteString("status", emailCampaign.Status);

            if (emailCampaign.DateAddedOption.IsSet)
                writer.WriteString("date_added", emailCampaign.DateAdded);

            if (emailCampaign.CustomStringOption.IsSet)
                writer.WriteString("custom_string", emailCampaign.CustomString);

            if (emailCampaign.SendCountOption.IsSet)
                writer.WriteNumber("send_count", emailCampaign.SendCountOption.Value!.Value);

            if (emailCampaign.OpenCountOption.IsSet)
                writer.WriteNumber("open_count", emailCampaign.OpenCountOption.Value!.Value);

            if (emailCampaign.ClickCountOption.IsSet)
                writer.WriteNumber("click_count", emailCampaign.ClickCountOption.Value!.Value);

            if (emailCampaign.HardBounceCountOption.IsSet)
                writer.WriteNumber("hard_bounce_count", emailCampaign.HardBounceCountOption.Value!.Value);

            if (emailCampaign.SoftBounceCountOption.IsSet)
                writer.WriteNumber("soft_bounce_count", emailCampaign.SoftBounceCountOption.Value!.Value);

            if (emailCampaign.AbuseCountOption.IsSet)
                writer.WriteNumber("abuse_count", emailCampaign.AbuseCountOption.Value!.Value);

            if (emailCampaign.UnsubscribeCountOption.IsSet)
                writer.WriteNumber("unsubscribe_count", emailCampaign.UnsubscribeCountOption.Value!.Value);

            if (emailCampaign.BodyOption.IsSet)
                writer.WriteString("body", emailCampaign.Body);

            if (emailCampaign.BodyPlainTextOption.IsSet)
                writer.WriteString("body_plain_text", emailCampaign.BodyPlainText);
        }
    }
}
