// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// Fax
    /// </summary>
    public partial class Fax : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Fax" /> class.
        /// </summary>
        /// <param name="userId">The ID of the user.</param>
        /// <param name="subaccountId">The ID of the subaccount.</param>
        /// <param name="listId">The ID of the list.</param>
        /// <param name="messageId">The ID of the message.</param>
        /// <param name="to">The recipient&#39;s phone number.</param>
        /// <param name="from">The sender&#39;s phone number.</param>
        /// <param name="carrier">The carrier associated with the message.</param>
        /// <param name="country">The country code.</param>
        /// <param name="customString">A custom string associated with the message.</param>
        /// <param name="schedule">The scheduled time for sending the message.</param>
        /// <param name="messagePages">The number of pages in the message.</param>
        /// <param name="messagePrice">The price of the message.</param>
        /// <param name="statusCode">The status code of the message.</param>
        /// <param name="statusText">The status text of the message.</param>
        /// <param name="dateAdded">The date when the message was added.</param>
        /// <param name="fromEmail">The sender&#39;s email address.</param>
        /// <param name="fileUrl">The URL of the file associated with the message.</param>
        /// <param name="status">The status of the message.</param>
        [JsonConstructor]
        public Fax(Option<int?> userId = default, Option<int?> subaccountId = default, Option<int?> listId = default, Option<string?> messageId = default, Option<string?> to = default, Option<string?> from = default, Option<string?> carrier = default, Option<string?> country = default, Option<string?> customString = default, Option<string?> schedule = default, Option<int?> messagePages = default, Option<string?> messagePrice = default, Option<string?> statusCode = default, Option<string?> statusText = default, Option<int?> dateAdded = default, Option<string?> fromEmail = default, Option<string?> fileUrl = default, Option<string?> status = default)
        {
            UserIdOption = userId;
            SubaccountIdOption = subaccountId;
            ListIdOption = listId;
            MessageIdOption = messageId;
            ToOption = to;
            FromOption = from;
            CarrierOption = carrier;
            CountryOption = country;
            CustomStringOption = customString;
            ScheduleOption = schedule;
            MessagePagesOption = messagePages;
            MessagePriceOption = messagePrice;
            StatusCodeOption = statusCode;
            StatusTextOption = statusText;
            DateAddedOption = dateAdded;
            FromEmailOption = fromEmail;
            FileUrlOption = fileUrl;
            StatusOption = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> UserIdOption { get; private set; }

        /// <summary>
        /// The ID of the user.
        /// </summary>
        /// <value>The ID of the user.</value>
        /* <example>1</example> */
        [JsonPropertyName("user_id")]
        public int? UserId { get { return this.UserIdOption.Value; } set { this.UserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SubaccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SubaccountIdOption { get; private set; }

        /// <summary>
        /// The ID of the subaccount.
        /// </summary>
        /// <value>The ID of the subaccount.</value>
        /* <example>1</example> */
        [JsonPropertyName("subaccount_id")]
        public int? SubaccountId { get { return this.SubaccountIdOption.Value; } set { this.SubaccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ListId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ListIdOption { get; private set; }

        /// <summary>
        /// The ID of the list.
        /// </summary>
        /// <value>The ID of the list.</value>
        [JsonPropertyName("list_id")]
        public int? ListId { get { return this.ListIdOption.Value; } set { this.ListIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of MessageId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageIdOption { get; private set; }

        /// <summary>
        /// The ID of the message.
        /// </summary>
        /// <value>The ID of the message.</value>
        /* <example>6BBEB11E-CAA6-4B04-8537-63619F3D6B37</example> */
        [JsonPropertyName("message_id")]
        public string? MessageId { get { return this.MessageIdOption.Value; } set { this.MessageIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of To
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ToOption { get; private set; }

        /// <summary>
        /// The recipient&#39;s phone number.
        /// </summary>
        /// <value>The recipient&#39;s phone number.</value>
        /* <example>+61261111122</example> */
        [JsonPropertyName("to")]
        public string? To { get { return this.ToOption.Value; } set { this.ToOption = new(value); } }

        /// <summary>
        /// Used to track the state of From
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FromOption { get; private set; }

        /// <summary>
        /// The sender&#39;s phone number.
        /// </summary>
        /// <value>The sender&#39;s phone number.</value>
        /* <example>+61298441484</example> */
        [JsonPropertyName("from")]
        public string? From { get { return this.FromOption.Value; } set { this.FromOption = new(value); } }

        /// <summary>
        /// Used to track the state of Carrier
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CarrierOption { get; private set; }

        /// <summary>
        /// The carrier associated with the message.
        /// </summary>
        /// <value>The carrier associated with the message.</value>
        [JsonPropertyName("carrier")]
        public string? Carrier { get { return this.CarrierOption.Value; } set { this.CarrierOption = new(value); } }

        /// <summary>
        /// Used to track the state of Country
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryOption { get; private set; }

        /// <summary>
        /// The country code.
        /// </summary>
        /// <value>The country code.</value>
        /* <example>AU</example> */
        [JsonPropertyName("country")]
        public string? Country { get { return this.CountryOption.Value; } set { this.CountryOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomString
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomStringOption { get; private set; }

        /// <summary>
        /// A custom string associated with the message.
        /// </summary>
        /// <value>A custom string associated with the message.</value>
        /* <example>custom_string</example> */
        [JsonPropertyName("custom_string")]
        public string? CustomString { get { return this.CustomStringOption.Value; } set { this.CustomStringOption = new(value); } }

        /// <summary>
        /// Used to track the state of Schedule
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ScheduleOption { get; private set; }

        /// <summary>
        /// The scheduled time for sending the message.
        /// </summary>
        /// <value>The scheduled time for sending the message.</value>
        /* <example>1436874701</example> */
        [JsonPropertyName("schedule")]
        public string? Schedule { get { return this.ScheduleOption.Value; } set { this.ScheduleOption = new(value); } }

        /// <summary>
        /// Used to track the state of MessagePages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MessagePagesOption { get; private set; }

        /// <summary>
        /// The number of pages in the message.
        /// </summary>
        /// <value>The number of pages in the message.</value>
        /* <example>6</example> */
        [JsonPropertyName("message_pages")]
        public int? MessagePages { get { return this.MessagePagesOption.Value; } set { this.MessagePagesOption = new(value); } }

        /// <summary>
        /// Used to track the state of MessagePrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessagePriceOption { get; private set; }

        /// <summary>
        /// The price of the message.
        /// </summary>
        /// <value>The price of the message.</value>
        /* <example>13.2000</example> */
        [JsonPropertyName("message_price")]
        public string? MessagePrice { get { return this.MessagePriceOption.Value; } set { this.MessagePriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of StatusCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusCodeOption { get; private set; }

        /// <summary>
        /// The status code of the message.
        /// </summary>
        /// <value>The status code of the message.</value>
        /* <example>201</example> */
        [JsonPropertyName("status_code")]
        public string? StatusCode { get { return this.StatusCodeOption.Value; } set { this.StatusCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of StatusText
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusTextOption { get; private set; }

        /// <summary>
        /// The status text of the message.
        /// </summary>
        /// <value>The status text of the message.</value>
        /* <example>Sent</example> */
        [JsonPropertyName("status_text")]
        public string? StatusText { get { return this.StatusTextOption.Value; } set { this.StatusTextOption = new(value); } }

        /// <summary>
        /// Used to track the state of DateAdded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DateAddedOption { get; private set; }

        /// <summary>
        /// The date when the message was added.
        /// </summary>
        /// <value>The date when the message was added.</value>
        /* <example>1457504350</example> */
        [JsonPropertyName("date_added")]
        public int? DateAdded { get { return this.DateAddedOption.Value; } set { this.DateAddedOption = new(value); } }

        /// <summary>
        /// Used to track the state of FromEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FromEmailOption { get; private set; }

        /// <summary>
        /// The sender&#39;s email address.
        /// </summary>
        /// <value>The sender&#39;s email address.</value>
        /* <example>john@doe.com</example> */
        [JsonPropertyName("from_email")]
        public string? FromEmail { get { return this.FromEmailOption.Value; } set { this.FromEmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of FileUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FileUrlOption { get; private set; }

        /// <summary>
        /// The URL of the file associated with the message.
        /// </summary>
        /// <value>The URL of the file associated with the message.</value>
        /* <example>https://rest.clicksend.com/files/98DDA1A4-8A74-4831-8FAF-CC4B4EBD8241.pdf</example> */
        [JsonPropertyName("_file_url")]
        public string? FileUrl { get { return this.FileUrlOption.Value; } set { this.FileUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// The status of the message.
        /// </summary>
        /// <value>The status of the message.</value>
        /* <example>SUCCESS</example> */
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Fax {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  SubaccountId: ").Append(SubaccountId).Append("\n");
            sb.Append("  ListId: ").Append(ListId).Append("\n");
            sb.Append("  MessageId: ").Append(MessageId).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  Carrier: ").Append(Carrier).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  CustomString: ").Append(CustomString).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  MessagePages: ").Append(MessagePages).Append("\n");
            sb.Append("  MessagePrice: ").Append(MessagePrice).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  StatusText: ").Append(StatusText).Append("\n");
            sb.Append("  DateAdded: ").Append(DateAdded).Append("\n");
            sb.Append("  FromEmail: ").Append(FromEmail).Append("\n");
            sb.Append("  FileUrl: ").Append(FileUrl).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Fax" />
    /// </summary>
    public class FaxJsonConverter : JsonConverter<Fax>
    {
        /// <summary>
        /// Deserializes json to <see cref="Fax" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Fax Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> userId = default;
            Option<int?> subaccountId = default;
            Option<int?> listId = default;
            Option<string?> messageId = default;
            Option<string?> to = default;
            Option<string?> from = default;
            Option<string?> carrier = default;
            Option<string?> country = default;
            Option<string?> customString = default;
            Option<string?> schedule = default;
            Option<int?> messagePages = default;
            Option<string?> messagePrice = default;
            Option<string?> statusCode = default;
            Option<string?> statusText = default;
            Option<int?> dateAdded = default;
            Option<string?> fromEmail = default;
            Option<string?> fileUrl = default;
            Option<string?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "user_id":
                            userId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "subaccount_id":
                            subaccountId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "list_id":
                            listId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "message_id":
                            messageId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "to":
                            to = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "from":
                            from = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "carrier":
                            carrier = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "country":
                            country = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "custom_string":
                            customString = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schedule":
                            schedule = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message_pages":
                            messagePages = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "message_price":
                            messagePrice = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status_code":
                            statusCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "status_text":
                            statusText = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "date_added":
                            dateAdded = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "from_email":
                            fromEmail = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "_file_url":
                            fileUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class Fax.");

            if (subaccountId.IsSet && subaccountId.Value == null)
                throw new ArgumentNullException(nameof(subaccountId), "Property is not nullable for class Fax.");

            if (messageId.IsSet && messageId.Value == null)
                throw new ArgumentNullException(nameof(messageId), "Property is not nullable for class Fax.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class Fax.");

            if (from.IsSet && from.Value == null)
                throw new ArgumentNullException(nameof(from), "Property is not nullable for class Fax.");

            if (carrier.IsSet && carrier.Value == null)
                throw new ArgumentNullException(nameof(carrier), "Property is not nullable for class Fax.");

            if (country.IsSet && country.Value == null)
                throw new ArgumentNullException(nameof(country), "Property is not nullable for class Fax.");

            if (customString.IsSet && customString.Value == null)
                throw new ArgumentNullException(nameof(customString), "Property is not nullable for class Fax.");

            if (schedule.IsSet && schedule.Value == null)
                throw new ArgumentNullException(nameof(schedule), "Property is not nullable for class Fax.");

            if (messagePages.IsSet && messagePages.Value == null)
                throw new ArgumentNullException(nameof(messagePages), "Property is not nullable for class Fax.");

            if (messagePrice.IsSet && messagePrice.Value == null)
                throw new ArgumentNullException(nameof(messagePrice), "Property is not nullable for class Fax.");

            if (dateAdded.IsSet && dateAdded.Value == null)
                throw new ArgumentNullException(nameof(dateAdded), "Property is not nullable for class Fax.");

            if (fromEmail.IsSet && fromEmail.Value == null)
                throw new ArgumentNullException(nameof(fromEmail), "Property is not nullable for class Fax.");

            if (fileUrl.IsSet && fileUrl.Value == null)
                throw new ArgumentNullException(nameof(fileUrl), "Property is not nullable for class Fax.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Fax.");

            return new Fax(userId, subaccountId, listId, messageId, to, from, carrier, country, customString, schedule, messagePages, messagePrice, statusCode, statusText, dateAdded, fromEmail, fileUrl, status);
        }

        /// <summary>
        /// Serializes a <see cref="Fax" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fax"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Fax fax, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fax, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Fax" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fax"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Fax fax, JsonSerializerOptions jsonSerializerOptions)
        {
            if (fax.MessageIdOption.IsSet && fax.MessageId == null)
                throw new ArgumentNullException(nameof(fax.MessageId), "Property is required for class Fax.");

            if (fax.ToOption.IsSet && fax.To == null)
                throw new ArgumentNullException(nameof(fax.To), "Property is required for class Fax.");

            if (fax.FromOption.IsSet && fax.From == null)
                throw new ArgumentNullException(nameof(fax.From), "Property is required for class Fax.");

            if (fax.CarrierOption.IsSet && fax.Carrier == null)
                throw new ArgumentNullException(nameof(fax.Carrier), "Property is required for class Fax.");

            if (fax.CountryOption.IsSet && fax.Country == null)
                throw new ArgumentNullException(nameof(fax.Country), "Property is required for class Fax.");

            if (fax.CustomStringOption.IsSet && fax.CustomString == null)
                throw new ArgumentNullException(nameof(fax.CustomString), "Property is required for class Fax.");

            if (fax.ScheduleOption.IsSet && fax.Schedule == null)
                throw new ArgumentNullException(nameof(fax.Schedule), "Property is required for class Fax.");

            if (fax.MessagePriceOption.IsSet && fax.MessagePrice == null)
                throw new ArgumentNullException(nameof(fax.MessagePrice), "Property is required for class Fax.");

            if (fax.FromEmailOption.IsSet && fax.FromEmail == null)
                throw new ArgumentNullException(nameof(fax.FromEmail), "Property is required for class Fax.");

            if (fax.FileUrlOption.IsSet && fax.FileUrl == null)
                throw new ArgumentNullException(nameof(fax.FileUrl), "Property is required for class Fax.");

            if (fax.StatusOption.IsSet && fax.Status == null)
                throw new ArgumentNullException(nameof(fax.Status), "Property is required for class Fax.");

            if (fax.UserIdOption.IsSet)
                writer.WriteNumber("user_id", fax.UserIdOption.Value!.Value);

            if (fax.SubaccountIdOption.IsSet)
                writer.WriteNumber("subaccount_id", fax.SubaccountIdOption.Value!.Value);

            if (fax.ListIdOption.IsSet)
                if (fax.ListIdOption.Value != null)
                    writer.WriteNumber("list_id", fax.ListIdOption.Value!.Value);
                else
                    writer.WriteNull("list_id");

            if (fax.MessageIdOption.IsSet)
                writer.WriteString("message_id", fax.MessageId);

            if (fax.ToOption.IsSet)
                writer.WriteString("to", fax.To);

            if (fax.FromOption.IsSet)
                writer.WriteString("from", fax.From);

            if (fax.CarrierOption.IsSet)
                writer.WriteString("carrier", fax.Carrier);

            if (fax.CountryOption.IsSet)
                writer.WriteString("country", fax.Country);

            if (fax.CustomStringOption.IsSet)
                writer.WriteString("custom_string", fax.CustomString);

            if (fax.ScheduleOption.IsSet)
                writer.WriteString("schedule", fax.Schedule);

            if (fax.MessagePagesOption.IsSet)
                writer.WriteNumber("message_pages", fax.MessagePagesOption.Value!.Value);

            if (fax.MessagePriceOption.IsSet)
                writer.WriteString("message_price", fax.MessagePrice);

            if (fax.StatusCodeOption.IsSet)
                if (fax.StatusCodeOption.Value != null)
                    writer.WriteString("status_code", fax.StatusCode);
                else
                    writer.WriteNull("status_code");

            if (fax.StatusTextOption.IsSet)
                if (fax.StatusTextOption.Value != null)
                    writer.WriteString("status_text", fax.StatusText);
                else
                    writer.WriteNull("status_text");

            if (fax.DateAddedOption.IsSet)
                writer.WriteNumber("date_added", fax.DateAddedOption.Value!.Value);

            if (fax.FromEmailOption.IsSet)
                writer.WriteString("from_email", fax.FromEmail);

            if (fax.FileUrlOption.IsSet)
                writer.WriteString("_file_url", fax.FileUrl);

            if (fax.StatusOption.IsSet)
                writer.WriteString("status", fax.Status);
        }
    }
}
