// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// RequestAlphaTagRequest
    /// </summary>
    public partial class RequestAlphaTagRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestAlphaTagRequest" /> class.
        /// </summary>
        /// <param name="alphaTag">alphaTag</param>
        /// <param name="reason">reason</param>
        /// <param name="countries">countries</param>
        /// <param name="businesses">businesses</param>
        [JsonConstructor]
        public RequestAlphaTagRequest(Option<string?> alphaTag = default, Option<string?> reason = default, Option<List<RequestAlphaTagRequest.CountriesEnum>?> countries = default, Option<List<RequestAlphaTagRequestBusinessesInner>?> businesses = default)
        {
            AlphaTagOption = alphaTag;
            ReasonOption = reason;
            CountriesOption = countries;
            BusinessesOption = businesses;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Countries
        /// </summary>
        public enum CountriesEnum
        {
            /// <summary>
            /// Enum AU for value: AU
            /// </summary>
            AU = 1
        }

        /// <summary>
        /// Returns a <see cref="CountriesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CountriesEnum CountriesEnumFromString(string value)
        {
            if (value.Equals("AU"))
                return CountriesEnum.AU;

            throw new NotImplementedException($"Could not convert value to type CountriesEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CountriesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CountriesEnum? CountriesEnumFromStringOrDefault(string value)
        {
            if (value.Equals("AU"))
                return CountriesEnum.AU;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CountriesEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CountriesEnumToJsonValue(CountriesEnum? value)
        {
            if (value == CountriesEnum.AU)
                return "AU";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of AlphaTag
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AlphaTagOption { get; private set; }

        /// <summary>
        /// Gets or Sets AlphaTag
        /// </summary>
        [JsonPropertyName("alpha_tag")]
        public string? AlphaTag { get { return this.AlphaTagOption.Value; } set { this.AlphaTagOption = new(value); } }

        /// <summary>
        /// Used to track the state of Reason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReasonOption { get; private set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [JsonPropertyName("reason")]
        public string? Reason { get { return this.ReasonOption.Value; } set { this.ReasonOption = new(value); } }

        /// <summary>
        /// Used to track the state of Countries
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<RequestAlphaTagRequest.CountriesEnum>?> CountriesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Countries
        /// </summary>
        [JsonPropertyName("countries")]
        public List<RequestAlphaTagRequest.CountriesEnum>? Countries { get { return this.CountriesOption.Value; } set { this.CountriesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Businesses
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<RequestAlphaTagRequestBusinessesInner>?> BusinessesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Businesses
        /// </summary>
        [JsonPropertyName("businesses")]
        public List<RequestAlphaTagRequestBusinessesInner>? Businesses { get { return this.BusinessesOption.Value; } set { this.BusinessesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequestAlphaTagRequest {\n");
            sb.Append("  AlphaTag: ").Append(AlphaTag).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Countries: ").Append(Countries).Append("\n");
            sb.Append("  Businesses: ").Append(Businesses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RequestAlphaTagRequest" />
    /// </summary>
    public class RequestAlphaTagRequestJsonConverter : JsonConverter<RequestAlphaTagRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="RequestAlphaTagRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RequestAlphaTagRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> alphaTag = default;
            Option<string?> reason = default;
            Option<List<RequestAlphaTagRequest.CountriesEnum>?> countries = default;
            Option<List<RequestAlphaTagRequestBusinessesInner>?> businesses = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "alpha_tag":
                            alphaTag = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "reason":
                            reason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "countries":
                            countries = new Option<List<RequestAlphaTagRequest.CountriesEnum>?>(JsonSerializer.Deserialize<List<RequestAlphaTagRequest.CountriesEnum>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "businesses":
                            businesses = new Option<List<RequestAlphaTagRequestBusinessesInner>?>(JsonSerializer.Deserialize<List<RequestAlphaTagRequestBusinessesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (alphaTag.IsSet && alphaTag.Value == null)
                throw new ArgumentNullException(nameof(alphaTag), "Property is not nullable for class RequestAlphaTagRequest.");

            if (reason.IsSet && reason.Value == null)
                throw new ArgumentNullException(nameof(reason), "Property is not nullable for class RequestAlphaTagRequest.");

            if (countries.IsSet && countries.Value == null)
                throw new ArgumentNullException(nameof(countries), "Property is not nullable for class RequestAlphaTagRequest.");

            if (businesses.IsSet && businesses.Value == null)
                throw new ArgumentNullException(nameof(businesses), "Property is not nullable for class RequestAlphaTagRequest.");

            return new RequestAlphaTagRequest(alphaTag, reason, countries, businesses);
        }

        /// <summary>
        /// Serializes a <see cref="RequestAlphaTagRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="requestAlphaTagRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RequestAlphaTagRequest requestAlphaTagRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, requestAlphaTagRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RequestAlphaTagRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="requestAlphaTagRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RequestAlphaTagRequest requestAlphaTagRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (requestAlphaTagRequest.AlphaTagOption.IsSet && requestAlphaTagRequest.AlphaTag == null)
                throw new ArgumentNullException(nameof(requestAlphaTagRequest.AlphaTag), "Property is required for class RequestAlphaTagRequest.");

            if (requestAlphaTagRequest.ReasonOption.IsSet && requestAlphaTagRequest.Reason == null)
                throw new ArgumentNullException(nameof(requestAlphaTagRequest.Reason), "Property is required for class RequestAlphaTagRequest.");

            if (requestAlphaTagRequest.CountriesOption.IsSet && requestAlphaTagRequest.Countries == null)
                throw new ArgumentNullException(nameof(requestAlphaTagRequest.Countries), "Property is required for class RequestAlphaTagRequest.");

            if (requestAlphaTagRequest.BusinessesOption.IsSet && requestAlphaTagRequest.Businesses == null)
                throw new ArgumentNullException(nameof(requestAlphaTagRequest.Businesses), "Property is required for class RequestAlphaTagRequest.");

            if (requestAlphaTagRequest.AlphaTagOption.IsSet)
                writer.WriteString("alpha_tag", requestAlphaTagRequest.AlphaTag);

            if (requestAlphaTagRequest.ReasonOption.IsSet)
                writer.WriteString("reason", requestAlphaTagRequest.Reason);

            if (requestAlphaTagRequest.CountriesOption.IsSet)
            {
                writer.WritePropertyName("countries");
                JsonSerializer.Serialize(writer, requestAlphaTagRequest.Countries, jsonSerializerOptions);
            }
            if (requestAlphaTagRequest.BusinessesOption.IsSet)
            {
                writer.WritePropertyName("businesses");
                JsonSerializer.Serialize(writer, requestAlphaTagRequest.Businesses, jsonSerializerOptions);
            }
        }
    }
}
