// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// SendVoiceMessageRequest
    /// </summary>
    public partial class SendVoiceMessageRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendVoiceMessageRequest" /> class.
        /// </summary>
        /// <param name="messages">messages</param>
        [JsonConstructor]
        public SendVoiceMessageRequest(Option<List<SendVoiceMessageRequestMessagesInner>?> messages = default)
        {
            MessagesOption = messages;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Messages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SendVoiceMessageRequestMessagesInner>?> MessagesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Messages
        /// </summary>
        [JsonPropertyName("messages")]
        public List<SendVoiceMessageRequestMessagesInner>? Messages { get { return this.MessagesOption.Value; } set { this.MessagesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendVoiceMessageRequest {\n");
            sb.Append("  Messages: ").Append(Messages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendVoiceMessageRequest" />
    /// </summary>
    public class SendVoiceMessageRequestJsonConverter : JsonConverter<SendVoiceMessageRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SendVoiceMessageRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendVoiceMessageRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<SendVoiceMessageRequestMessagesInner>?> messages = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "messages":
                            messages = new Option<List<SendVoiceMessageRequestMessagesInner>?>(JsonSerializer.Deserialize<List<SendVoiceMessageRequestMessagesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (messages.IsSet && messages.Value == null)
                throw new ArgumentNullException(nameof(messages), "Property is not nullable for class SendVoiceMessageRequest.");

            return new SendVoiceMessageRequest(messages);
        }

        /// <summary>
        /// Serializes a <see cref="SendVoiceMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendVoiceMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SendVoiceMessageRequest sendVoiceMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendVoiceMessageRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendVoiceMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendVoiceMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SendVoiceMessageRequest sendVoiceMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendVoiceMessageRequest.MessagesOption.IsSet && sendVoiceMessageRequest.Messages == null)
                throw new ArgumentNullException(nameof(sendVoiceMessageRequest.Messages), "Property is required for class SendVoiceMessageRequest.");

            if (sendVoiceMessageRequest.MessagesOption.IsSet)
            {
                writer.WritePropertyName("messages");
                JsonSerializer.Serialize(writer, sendVoiceMessageRequest.Messages, jsonSerializerOptions);
            }
        }
    }
}
