// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// SendersInner
    /// </summary>
    public partial class SendersInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendersInner" /> class.
        /// </summary>
        /// <param name="recipientCountryCode">Recipient ISO country code</param>
        /// <param name="senderId">The sender ID must be either an alpha tag or a phone number. It is a required field unless the sender type is a &#x60;shared_longcode&#x60;.   If the sender ID is an **alpha tag**, it must be between 3 and 11 characters long and contains only letters, numbers, and pluses. </param>
        /// <param name="senderType">The type of sender ID, it only supports &#x60;shared_longcode&#x60; at the moment.</param>
        /// <param name="senderCountryCode">The ISO 3166-1 alpha-2 country code that identifies the country associated with the sender’s number in a shared pool. This is affected only when &#x60;sender_type&#x60; is set to &#x60;shared_longcode&#x60; to determine the appropriate number based on the sender’s geographic location. If this field is not provided or left empty, it will default to the recipient&#39;s country code. </param>
        [JsonConstructor]
        public SendersInner(string recipientCountryCode, Option<string?> senderId = default, Option<SenderTypeEnum?> senderType = default, Option<string?> senderCountryCode = default)
        {
            RecipientCountryCode = recipientCountryCode;
            SenderIdOption = senderId;
            SenderTypeOption = senderType;
            SenderCountryCodeOption = senderCountryCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The type of sender ID, it only supports &#x60;shared_longcode&#x60; at the moment.
        /// </summary>
        /// <value>The type of sender ID, it only supports &#x60;shared_longcode&#x60; at the moment.</value>
        public enum SenderTypeEnum
        {
            /// <summary>
            /// Enum SharedLongcode for value: shared_longcode
            /// </summary>
            SharedLongcode = 1
        }

        /// <summary>
        /// Returns a <see cref="SenderTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SenderTypeEnum SenderTypeEnumFromString(string value)
        {
            if (value.Equals("shared_longcode"))
                return SenderTypeEnum.SharedLongcode;

            throw new NotImplementedException($"Could not convert value to type SenderTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SenderTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SenderTypeEnum? SenderTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("shared_longcode"))
                return SenderTypeEnum.SharedLongcode;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SenderTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string SenderTypeEnumToJsonValue(SenderTypeEnum? value)
        {
            if (value == SenderTypeEnum.SharedLongcode)
                return "shared_longcode";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of SenderType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SenderTypeEnum?> SenderTypeOption { get; private set; }

        /// <summary>
        /// The type of sender ID, it only supports &#x60;shared_longcode&#x60; at the moment.
        /// </summary>
        /// <value>The type of sender ID, it only supports &#x60;shared_longcode&#x60; at the moment.</value>
        [JsonPropertyName("sender_type")]
        public SenderTypeEnum? SenderType { get { return this.SenderTypeOption.Value; } set { this.SenderTypeOption = new(value); } }

        /// <summary>
        /// Recipient ISO country code
        /// </summary>
        /// <value>Recipient ISO country code</value>
        [JsonPropertyName("recipient_country_code")]
        public string RecipientCountryCode { get; set; }

        /// <summary>
        /// Used to track the state of SenderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SenderIdOption { get; private set; }

        /// <summary>
        /// The sender ID must be either an alpha tag or a phone number. It is a required field unless the sender type is a &#x60;shared_longcode&#x60;.   If the sender ID is an **alpha tag**, it must be between 3 and 11 characters long and contains only letters, numbers, and pluses. 
        /// </summary>
        /// <value>The sender ID must be either an alpha tag or a phone number. It is a required field unless the sender type is a &#x60;shared_longcode&#x60;.   If the sender ID is an **alpha tag**, it must be between 3 and 11 characters long and contains only letters, numbers, and pluses. </value>
        [JsonPropertyName("sender_id")]
        public string? SenderId { get { return this.SenderIdOption.Value; } set { this.SenderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SenderCountryCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SenderCountryCodeOption { get; private set; }

        /// <summary>
        /// The ISO 3166-1 alpha-2 country code that identifies the country associated with the sender’s number in a shared pool. This is affected only when &#x60;sender_type&#x60; is set to &#x60;shared_longcode&#x60; to determine the appropriate number based on the sender’s geographic location. If this field is not provided or left empty, it will default to the recipient&#39;s country code. 
        /// </summary>
        /// <value>The ISO 3166-1 alpha-2 country code that identifies the country associated with the sender’s number in a shared pool. This is affected only when &#x60;sender_type&#x60; is set to &#x60;shared_longcode&#x60; to determine the appropriate number based on the sender’s geographic location. If this field is not provided or left empty, it will default to the recipient&#39;s country code. </value>
        [JsonPropertyName("sender_country_code")]
        public string? SenderCountryCode { get { return this.SenderCountryCodeOption.Value; } set { this.SenderCountryCodeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendersInner {\n");
            sb.Append("  RecipientCountryCode: ").Append(RecipientCountryCode).Append("\n");
            sb.Append("  SenderId: ").Append(SenderId).Append("\n");
            sb.Append("  SenderType: ").Append(SenderType).Append("\n");
            sb.Append("  SenderCountryCode: ").Append(SenderCountryCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendersInner" />
    /// </summary>
    public class SendersInnerJsonConverter : JsonConverter<SendersInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="SendersInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendersInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> recipientCountryCode = default;
            Option<string?> senderId = default;
            Option<SendersInner.SenderTypeEnum?> senderType = default;
            Option<string?> senderCountryCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "recipient_country_code":
                            recipientCountryCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sender_id":
                            senderId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sender_type":
                            string? senderTypeRawValue = utf8JsonReader.GetString();
                            if (senderTypeRawValue != null)
                                senderType = new Option<SendersInner.SenderTypeEnum?>(SendersInner.SenderTypeEnumFromStringOrDefault(senderTypeRawValue));
                            break;
                        case "sender_country_code":
                            senderCountryCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!recipientCountryCode.IsSet)
                throw new ArgumentException("Property is required for class SendersInner.", nameof(recipientCountryCode));

            if (recipientCountryCode.IsSet && recipientCountryCode.Value == null)
                throw new ArgumentNullException(nameof(recipientCountryCode), "Property is not nullable for class SendersInner.");

            if (senderId.IsSet && senderId.Value == null)
                throw new ArgumentNullException(nameof(senderId), "Property is not nullable for class SendersInner.");

            if (senderType.IsSet && senderType.Value == null)
                throw new ArgumentNullException(nameof(senderType), "Property is not nullable for class SendersInner.");

            if (senderCountryCode.IsSet && senderCountryCode.Value == null)
                throw new ArgumentNullException(nameof(senderCountryCode), "Property is not nullable for class SendersInner.");

            return new SendersInner(recipientCountryCode.Value!, senderId, senderType, senderCountryCode);
        }

        /// <summary>
        /// Serializes a <see cref="SendersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SendersInner sendersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendersInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SendersInner sendersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendersInner.RecipientCountryCode == null)
                throw new ArgumentNullException(nameof(sendersInner.RecipientCountryCode), "Property is required for class SendersInner.");

            if (sendersInner.SenderIdOption.IsSet && sendersInner.SenderId == null)
                throw new ArgumentNullException(nameof(sendersInner.SenderId), "Property is required for class SendersInner.");

            if (sendersInner.SenderCountryCodeOption.IsSet && sendersInner.SenderCountryCode == null)
                throw new ArgumentNullException(nameof(sendersInner.SenderCountryCode), "Property is required for class SendersInner.");

            writer.WriteString("recipient_country_code", sendersInner.RecipientCountryCode);

            if (sendersInner.SenderIdOption.IsSet)
                writer.WriteString("sender_id", sendersInner.SenderId);

            var senderTypeRawValue = SendersInner.SenderTypeEnumToJsonValue(sendersInner.SenderTypeOption.Value!.Value);
            writer.WriteString("sender_type", senderTypeRawValue);
            if (sendersInner.SenderCountryCodeOption.IsSet)
                writer.WriteString("sender_country_code", sendersInner.SenderCountryCode);
        }
    }
}
