// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// UpdateFaxDeliveryReceiptRuleRequest
    /// </summary>
    public partial class UpdateFaxDeliveryReceiptRuleRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateFaxDeliveryReceiptRuleRequest" /> class.
        /// </summary>
        /// <param name="actionAddress">actionAddress</param>
        [JsonConstructor]
        public UpdateFaxDeliveryReceiptRuleRequest(Option<string?> actionAddress = default)
        {
            ActionAddressOption = actionAddress;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ActionAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActionAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets ActionAddress
        /// </summary>
        [JsonPropertyName("action_address")]
        public string? ActionAddress { get { return this.ActionAddressOption.Value; } set { this.ActionAddressOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateFaxDeliveryReceiptRuleRequest {\n");
            sb.Append("  ActionAddress: ").Append(ActionAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateFaxDeliveryReceiptRuleRequest" />
    /// </summary>
    public class UpdateFaxDeliveryReceiptRuleRequestJsonConverter : JsonConverter<UpdateFaxDeliveryReceiptRuleRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateFaxDeliveryReceiptRuleRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateFaxDeliveryReceiptRuleRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> actionAddress = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "action_address":
                            actionAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (actionAddress.IsSet && actionAddress.Value == null)
                throw new ArgumentNullException(nameof(actionAddress), "Property is not nullable for class UpdateFaxDeliveryReceiptRuleRequest.");

            return new UpdateFaxDeliveryReceiptRuleRequest(actionAddress);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateFaxDeliveryReceiptRuleRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateFaxDeliveryReceiptRuleRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateFaxDeliveryReceiptRuleRequest updateFaxDeliveryReceiptRuleRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateFaxDeliveryReceiptRuleRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateFaxDeliveryReceiptRuleRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateFaxDeliveryReceiptRuleRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateFaxDeliveryReceiptRuleRequest updateFaxDeliveryReceiptRuleRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateFaxDeliveryReceiptRuleRequest.ActionAddressOption.IsSet && updateFaxDeliveryReceiptRuleRequest.ActionAddress == null)
                throw new ArgumentNullException(nameof(updateFaxDeliveryReceiptRuleRequest.ActionAddress), "Property is required for class UpdateFaxDeliveryReceiptRuleRequest.");

            if (updateFaxDeliveryReceiptRuleRequest.ActionAddressOption.IsSet)
                writer.WriteString("action_address", updateFaxDeliveryReceiptRuleRequest.ActionAddress);
        }
    }
}
