// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// UserEmailTemplate
    /// </summary>
    public partial class UserEmailTemplate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserEmailTemplate" /> class.
        /// </summary>
        /// <param name="templateId">The unique identifier for the template.</param>
        /// <param name="templateIdMaster">The unique identifier for the template.</param>
        /// <param name="templateName">The name of the template.</param>
        /// <param name="body">The body of the template.</param>
        [JsonConstructor]
        public UserEmailTemplate(Option<int?> templateId = default, Option<int?> templateIdMaster = default, Option<string?> templateName = default, Option<string?> body = default)
        {
            TemplateIdOption = templateId;
            TemplateIdMasterOption = templateIdMaster;
            TemplateNameOption = templateName;
            BodyOption = body;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TemplateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TemplateIdOption { get; private set; }

        /// <summary>
        /// The unique identifier for the template.
        /// </summary>
        /// <value>The unique identifier for the template.</value>
        /* <example>292</example> */
        [JsonPropertyName("template_id")]
        public int? TemplateId { get { return this.TemplateIdOption.Value; } set { this.TemplateIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TemplateIdMaster
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TemplateIdMasterOption { get; private set; }

        /// <summary>
        /// The unique identifier for the template.
        /// </summary>
        /// <value>The unique identifier for the template.</value>
        /* <example>57</example> */
        [JsonPropertyName("template_id_master")]
        public int? TemplateIdMaster { get { return this.TemplateIdMasterOption.Value; } set { this.TemplateIdMasterOption = new(value); } }

        /// <summary>
        /// Used to track the state of TemplateName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TemplateNameOption { get; private set; }

        /// <summary>
        /// The name of the template.
        /// </summary>
        /// <value>The name of the template.</value>
        /* <example>new minion template!</example> */
        [JsonPropertyName("template_name")]
        public string? TemplateName { get { return this.TemplateNameOption.Value; } set { this.TemplateNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Body
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BodyOption { get; private set; }

        /// <summary>
        /// The body of the template.
        /// </summary>
        /// <value>The body of the template.</value>
        /* <example>&lt;div id&#x3D;&quot;nb_wrapper&quot;&gt;&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;...</example> */
        [JsonPropertyName("body")]
        public string? Body { get { return this.BodyOption.Value; } set { this.BodyOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserEmailTemplate {\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  TemplateIdMaster: ").Append(TemplateIdMaster).Append("\n");
            sb.Append("  TemplateName: ").Append(TemplateName).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserEmailTemplate" />
    /// </summary>
    public class UserEmailTemplateJsonConverter : JsonConverter<UserEmailTemplate>
    {
        /// <summary>
        /// Deserializes json to <see cref="UserEmailTemplate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserEmailTemplate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> templateId = default;
            Option<int?> templateIdMaster = default;
            Option<string?> templateName = default;
            Option<string?> body = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "template_id":
                            templateId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "template_id_master":
                            templateIdMaster = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "template_name":
                            templateName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "body":
                            body = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (templateId.IsSet && templateId.Value == null)
                throw new ArgumentNullException(nameof(templateId), "Property is not nullable for class UserEmailTemplate.");

            if (templateIdMaster.IsSet && templateIdMaster.Value == null)
                throw new ArgumentNullException(nameof(templateIdMaster), "Property is not nullable for class UserEmailTemplate.");

            if (templateName.IsSet && templateName.Value == null)
                throw new ArgumentNullException(nameof(templateName), "Property is not nullable for class UserEmailTemplate.");

            if (body.IsSet && body.Value == null)
                throw new ArgumentNullException(nameof(body), "Property is not nullable for class UserEmailTemplate.");

            return new UserEmailTemplate(templateId, templateIdMaster, templateName, body);
        }

        /// <summary>
        /// Serializes a <see cref="UserEmailTemplate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userEmailTemplate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserEmailTemplate userEmailTemplate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userEmailTemplate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserEmailTemplate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userEmailTemplate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserEmailTemplate userEmailTemplate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (userEmailTemplate.TemplateNameOption.IsSet && userEmailTemplate.TemplateName == null)
                throw new ArgumentNullException(nameof(userEmailTemplate.TemplateName), "Property is required for class UserEmailTemplate.");

            if (userEmailTemplate.BodyOption.IsSet && userEmailTemplate.Body == null)
                throw new ArgumentNullException(nameof(userEmailTemplate.Body), "Property is required for class UserEmailTemplate.");

            if (userEmailTemplate.TemplateIdOption.IsSet)
                writer.WriteNumber("template_id", userEmailTemplate.TemplateIdOption.Value!.Value);

            if (userEmailTemplate.TemplateIdMasterOption.IsSet)
                writer.WriteNumber("template_id_master", userEmailTemplate.TemplateIdMasterOption.Value!.Value);

            if (userEmailTemplate.TemplateNameOption.IsSet)
                writer.WriteString("template_name", userEmailTemplate.TemplateName);

            if (userEmailTemplate.BodyOption.IsSet)
                writer.WriteString("body", userEmailTemplate.Body);
        }
    }
}
