// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// ViewAvailableNumbersDataAllOfDataInner
    /// </summary>
    public partial class ViewAvailableNumbersDataAllOfDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ViewAvailableNumbersDataAllOfDataInner" /> class.
        /// </summary>
        /// <param name="country">The country code of the number.</param>
        /// <param name="countryName">The country name of the number.</param>
        /// <param name="dedicatedNumber">The dedicated number.</param>
        /// <param name="priceSetup">The setup price of the number.</param>
        /// <param name="priceMonthly">The monthly price of the number.</param>
        /// <param name="priceTotal">The total price of the number.</param>
        /// <param name="addressRequirement">The address requirement for the number.  &lt;br&gt; &#x60;local&#x60;: requires an address that corresponds  to the phone number&#39;s prefix.</param>
        [JsonConstructor]
        public ViewAvailableNumbersDataAllOfDataInner(Option<string?> country = default, Option<string?> countryName = default, Option<string?> dedicatedNumber = default, Option<string?> priceSetup = default, Option<string?> priceMonthly = default, Option<string?> priceTotal = default, Option<string?> addressRequirement = default)
        {
            CountryOption = country;
            CountryNameOption = countryName;
            DedicatedNumberOption = dedicatedNumber;
            PriceSetupOption = priceSetup;
            PriceMonthlyOption = priceMonthly;
            PriceTotalOption = priceTotal;
            AddressRequirementOption = addressRequirement;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Country
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryOption { get; private set; }

        /// <summary>
        /// The country code of the number.
        /// </summary>
        /// <value>The country code of the number.</value>
        [JsonPropertyName("country")]
        public string? Country { get { return this.CountryOption.Value; } set { this.CountryOption = new(value); } }

        /// <summary>
        /// Used to track the state of CountryName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryNameOption { get; private set; }

        /// <summary>
        /// The country name of the number.
        /// </summary>
        /// <value>The country name of the number.</value>
        [JsonPropertyName("country_name")]
        public string? CountryName { get { return this.CountryNameOption.Value; } set { this.CountryNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of DedicatedNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DedicatedNumberOption { get; private set; }

        /// <summary>
        /// The dedicated number.
        /// </summary>
        /// <value>The dedicated number.</value>
        [JsonPropertyName("dedicated_number")]
        public string? DedicatedNumber { get { return this.DedicatedNumberOption.Value; } set { this.DedicatedNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of PriceSetup
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PriceSetupOption { get; private set; }

        /// <summary>
        /// The setup price of the number.
        /// </summary>
        /// <value>The setup price of the number.</value>
        [JsonPropertyName("price_setup")]
        public string? PriceSetup { get { return this.PriceSetupOption.Value; } set { this.PriceSetupOption = new(value); } }

        /// <summary>
        /// Used to track the state of PriceMonthly
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PriceMonthlyOption { get; private set; }

        /// <summary>
        /// The monthly price of the number.
        /// </summary>
        /// <value>The monthly price of the number.</value>
        [JsonPropertyName("price_monthly")]
        public string? PriceMonthly { get { return this.PriceMonthlyOption.Value; } set { this.PriceMonthlyOption = new(value); } }

        /// <summary>
        /// Used to track the state of PriceTotal
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PriceTotalOption { get; private set; }

        /// <summary>
        /// The total price of the number.
        /// </summary>
        /// <value>The total price of the number.</value>
        [JsonPropertyName("price_total")]
        public string? PriceTotal { get { return this.PriceTotalOption.Value; } set { this.PriceTotalOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressRequirement
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressRequirementOption { get; private set; }

        /// <summary>
        /// The address requirement for the number.  &lt;br&gt; &#x60;local&#x60;: requires an address that corresponds  to the phone number&#39;s prefix.
        /// </summary>
        /// <value>The address requirement for the number.  &lt;br&gt; &#x60;local&#x60;: requires an address that corresponds  to the phone number&#39;s prefix.</value>
        [JsonPropertyName("address_requirement")]
        public string? AddressRequirement { get { return this.AddressRequirementOption.Value; } set { this.AddressRequirementOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ViewAvailableNumbersDataAllOfDataInner {\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  CountryName: ").Append(CountryName).Append("\n");
            sb.Append("  DedicatedNumber: ").Append(DedicatedNumber).Append("\n");
            sb.Append("  PriceSetup: ").Append(PriceSetup).Append("\n");
            sb.Append("  PriceMonthly: ").Append(PriceMonthly).Append("\n");
            sb.Append("  PriceTotal: ").Append(PriceTotal).Append("\n");
            sb.Append("  AddressRequirement: ").Append(AddressRequirement).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ViewAvailableNumbersDataAllOfDataInner" />
    /// </summary>
    public class ViewAvailableNumbersDataAllOfDataInnerJsonConverter : JsonConverter<ViewAvailableNumbersDataAllOfDataInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="ViewAvailableNumbersDataAllOfDataInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ViewAvailableNumbersDataAllOfDataInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> country = default;
            Option<string?> countryName = default;
            Option<string?> dedicatedNumber = default;
            Option<string?> priceSetup = default;
            Option<string?> priceMonthly = default;
            Option<string?> priceTotal = default;
            Option<string?> addressRequirement = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "country":
                            country = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "country_name":
                            countryName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "dedicated_number":
                            dedicatedNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "price_setup":
                            priceSetup = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "price_monthly":
                            priceMonthly = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "price_total":
                            priceTotal = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address_requirement":
                            addressRequirement = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (country.IsSet && country.Value == null)
                throw new ArgumentNullException(nameof(country), "Property is not nullable for class ViewAvailableNumbersDataAllOfDataInner.");

            if (countryName.IsSet && countryName.Value == null)
                throw new ArgumentNullException(nameof(countryName), "Property is not nullable for class ViewAvailableNumbersDataAllOfDataInner.");

            if (dedicatedNumber.IsSet && dedicatedNumber.Value == null)
                throw new ArgumentNullException(nameof(dedicatedNumber), "Property is not nullable for class ViewAvailableNumbersDataAllOfDataInner.");

            if (priceSetup.IsSet && priceSetup.Value == null)
                throw new ArgumentNullException(nameof(priceSetup), "Property is not nullable for class ViewAvailableNumbersDataAllOfDataInner.");

            if (priceMonthly.IsSet && priceMonthly.Value == null)
                throw new ArgumentNullException(nameof(priceMonthly), "Property is not nullable for class ViewAvailableNumbersDataAllOfDataInner.");

            if (priceTotal.IsSet && priceTotal.Value == null)
                throw new ArgumentNullException(nameof(priceTotal), "Property is not nullable for class ViewAvailableNumbersDataAllOfDataInner.");

            return new ViewAvailableNumbersDataAllOfDataInner(country, countryName, dedicatedNumber, priceSetup, priceMonthly, priceTotal, addressRequirement);
        }

        /// <summary>
        /// Serializes a <see cref="ViewAvailableNumbersDataAllOfDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="viewAvailableNumbersDataAllOfDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ViewAvailableNumbersDataAllOfDataInner viewAvailableNumbersDataAllOfDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, viewAvailableNumbersDataAllOfDataInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ViewAvailableNumbersDataAllOfDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="viewAvailableNumbersDataAllOfDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ViewAvailableNumbersDataAllOfDataInner viewAvailableNumbersDataAllOfDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (viewAvailableNumbersDataAllOfDataInner.CountryOption.IsSet && viewAvailableNumbersDataAllOfDataInner.Country == null)
                throw new ArgumentNullException(nameof(viewAvailableNumbersDataAllOfDataInner.Country), "Property is required for class ViewAvailableNumbersDataAllOfDataInner.");

            if (viewAvailableNumbersDataAllOfDataInner.CountryNameOption.IsSet && viewAvailableNumbersDataAllOfDataInner.CountryName == null)
                throw new ArgumentNullException(nameof(viewAvailableNumbersDataAllOfDataInner.CountryName), "Property is required for class ViewAvailableNumbersDataAllOfDataInner.");

            if (viewAvailableNumbersDataAllOfDataInner.DedicatedNumberOption.IsSet && viewAvailableNumbersDataAllOfDataInner.DedicatedNumber == null)
                throw new ArgumentNullException(nameof(viewAvailableNumbersDataAllOfDataInner.DedicatedNumber), "Property is required for class ViewAvailableNumbersDataAllOfDataInner.");

            if (viewAvailableNumbersDataAllOfDataInner.PriceSetupOption.IsSet && viewAvailableNumbersDataAllOfDataInner.PriceSetup == null)
                throw new ArgumentNullException(nameof(viewAvailableNumbersDataAllOfDataInner.PriceSetup), "Property is required for class ViewAvailableNumbersDataAllOfDataInner.");

            if (viewAvailableNumbersDataAllOfDataInner.PriceMonthlyOption.IsSet && viewAvailableNumbersDataAllOfDataInner.PriceMonthly == null)
                throw new ArgumentNullException(nameof(viewAvailableNumbersDataAllOfDataInner.PriceMonthly), "Property is required for class ViewAvailableNumbersDataAllOfDataInner.");

            if (viewAvailableNumbersDataAllOfDataInner.PriceTotalOption.IsSet && viewAvailableNumbersDataAllOfDataInner.PriceTotal == null)
                throw new ArgumentNullException(nameof(viewAvailableNumbersDataAllOfDataInner.PriceTotal), "Property is required for class ViewAvailableNumbersDataAllOfDataInner.");

            if (viewAvailableNumbersDataAllOfDataInner.CountryOption.IsSet)
                writer.WriteString("country", viewAvailableNumbersDataAllOfDataInner.Country);

            if (viewAvailableNumbersDataAllOfDataInner.CountryNameOption.IsSet)
                writer.WriteString("country_name", viewAvailableNumbersDataAllOfDataInner.CountryName);

            if (viewAvailableNumbersDataAllOfDataInner.DedicatedNumberOption.IsSet)
                writer.WriteString("dedicated_number", viewAvailableNumbersDataAllOfDataInner.DedicatedNumber);

            if (viewAvailableNumbersDataAllOfDataInner.PriceSetupOption.IsSet)
                writer.WriteString("price_setup", viewAvailableNumbersDataAllOfDataInner.PriceSetup);

            if (viewAvailableNumbersDataAllOfDataInner.PriceMonthlyOption.IsSet)
                writer.WriteString("price_monthly", viewAvailableNumbersDataAllOfDataInner.PriceMonthly);

            if (viewAvailableNumbersDataAllOfDataInner.PriceTotalOption.IsSet)
                writer.WriteString("price_total", viewAvailableNumbersDataAllOfDataInner.PriceTotal);

            if (viewAvailableNumbersDataAllOfDataInner.AddressRequirementOption.IsSet)
                if (viewAvailableNumbersDataAllOfDataInner.AddressRequirementOption.Value != null)
                    writer.WriteString("address_requirement", viewAvailableNumbersDataAllOfDataInner.AddressRequirement);
                else
                    writer.WriteNull("address_requirement");
        }
    }
}
