// <auto-generated>
/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ClickSend.Client;

namespace ClickSend.Model
{
    /// <summary>
    /// ViewSmsStatisticsDataTotal
    /// </summary>
    public partial class ViewSmsStatisticsDataTotal : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ViewSmsStatisticsDataTotal" /> class.
        /// </summary>
        /// <param name="outbound">outbound</param>
        /// <param name="inbound">inbound</param>
        /// <param name="bounced">bounced</param>
        [JsonConstructor]
        public ViewSmsStatisticsDataTotal(Option<ViewVoiceStatisticsDataTotalOutbound?> outbound = default, Option<CancelAllSmsData?> inbound = default, Option<CancelAllSmsData?> bounced = default)
        {
            OutboundOption = outbound;
            InboundOption = inbound;
            BouncedOption = bounced;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Outbound
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ViewVoiceStatisticsDataTotalOutbound?> OutboundOption { get; private set; }

        /// <summary>
        /// Gets or Sets Outbound
        /// </summary>
        [JsonPropertyName("outbound")]
        public ViewVoiceStatisticsDataTotalOutbound? Outbound { get { return this.OutboundOption.Value; } set { this.OutboundOption = new(value); } }

        /// <summary>
        /// Used to track the state of Inbound
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CancelAllSmsData?> InboundOption { get; private set; }

        /// <summary>
        /// Gets or Sets Inbound
        /// </summary>
        [JsonPropertyName("inbound")]
        public CancelAllSmsData? Inbound { get { return this.InboundOption.Value; } set { this.InboundOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bounced
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CancelAllSmsData?> BouncedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bounced
        /// </summary>
        [JsonPropertyName("bounced")]
        public CancelAllSmsData? Bounced { get { return this.BouncedOption.Value; } set { this.BouncedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ViewSmsStatisticsDataTotal {\n");
            sb.Append("  Outbound: ").Append(Outbound).Append("\n");
            sb.Append("  Inbound: ").Append(Inbound).Append("\n");
            sb.Append("  Bounced: ").Append(Bounced).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ViewSmsStatisticsDataTotal" />
    /// </summary>
    public class ViewSmsStatisticsDataTotalJsonConverter : JsonConverter<ViewSmsStatisticsDataTotal>
    {
        /// <summary>
        /// Deserializes json to <see cref="ViewSmsStatisticsDataTotal" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ViewSmsStatisticsDataTotal Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ViewVoiceStatisticsDataTotalOutbound?> outbound = default;
            Option<CancelAllSmsData?> inbound = default;
            Option<CancelAllSmsData?> bounced = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "outbound":
                            outbound = new Option<ViewVoiceStatisticsDataTotalOutbound?>(JsonSerializer.Deserialize<ViewVoiceStatisticsDataTotalOutbound>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "inbound":
                            inbound = new Option<CancelAllSmsData?>(JsonSerializer.Deserialize<CancelAllSmsData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "bounced":
                            bounced = new Option<CancelAllSmsData?>(JsonSerializer.Deserialize<CancelAllSmsData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (outbound.IsSet && outbound.Value == null)
                throw new ArgumentNullException(nameof(outbound), "Property is not nullable for class ViewSmsStatisticsDataTotal.");

            if (inbound.IsSet && inbound.Value == null)
                throw new ArgumentNullException(nameof(inbound), "Property is not nullable for class ViewSmsStatisticsDataTotal.");

            if (bounced.IsSet && bounced.Value == null)
                throw new ArgumentNullException(nameof(bounced), "Property is not nullable for class ViewSmsStatisticsDataTotal.");

            return new ViewSmsStatisticsDataTotal(outbound, inbound, bounced);
        }

        /// <summary>
        /// Serializes a <see cref="ViewSmsStatisticsDataTotal" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="viewSmsStatisticsDataTotal"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ViewSmsStatisticsDataTotal viewSmsStatisticsDataTotal, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, viewSmsStatisticsDataTotal, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ViewSmsStatisticsDataTotal" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="viewSmsStatisticsDataTotal"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ViewSmsStatisticsDataTotal viewSmsStatisticsDataTotal, JsonSerializerOptions jsonSerializerOptions)
        {
            if (viewSmsStatisticsDataTotal.OutboundOption.IsSet && viewSmsStatisticsDataTotal.Outbound == null)
                throw new ArgumentNullException(nameof(viewSmsStatisticsDataTotal.Outbound), "Property is required for class ViewSmsStatisticsDataTotal.");

            if (viewSmsStatisticsDataTotal.InboundOption.IsSet && viewSmsStatisticsDataTotal.Inbound == null)
                throw new ArgumentNullException(nameof(viewSmsStatisticsDataTotal.Inbound), "Property is required for class ViewSmsStatisticsDataTotal.");

            if (viewSmsStatisticsDataTotal.BouncedOption.IsSet && viewSmsStatisticsDataTotal.Bounced == null)
                throw new ArgumentNullException(nameof(viewSmsStatisticsDataTotal.Bounced), "Property is required for class ViewSmsStatisticsDataTotal.");

            if (viewSmsStatisticsDataTotal.OutboundOption.IsSet)
            {
                writer.WritePropertyName("outbound");
                JsonSerializer.Serialize(writer, viewSmsStatisticsDataTotal.Outbound, jsonSerializerOptions);
            }
            if (viewSmsStatisticsDataTotal.InboundOption.IsSet)
            {
                writer.WritePropertyName("inbound");
                JsonSerializer.Serialize(writer, viewSmsStatisticsDataTotal.Inbound, jsonSerializerOptions);
            }
            if (viewSmsStatisticsDataTotal.BouncedOption.IsSet)
            {
                writer.WritePropertyName("bounced");
                JsonSerializer.Serialize(writer, viewSmsStatisticsDataTotal.Bounced, jsonSerializerOptions);
            }
        }
    }
}
