/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ClickSend.Model;
using ClickSend.Client;
using System.Reflection;

namespace ClickSend.Test.Model
{
    /// <summary>
    ///  Class for testing EmailCampaign
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailCampaignTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailCampaign
        //private EmailCampaign instance;

        public EmailCampaignTests()
        {
            // TODO uncomment below to create an instance of EmailCampaign
            //instance = new EmailCampaign();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailCampaign
        /// </summary>
        [Fact]
        public void EmailCampaignInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailCampaign
            //Assert.IsType<EmailCampaign>(instance);
        }

        /// <summary>
        /// Test the property 'EmailCampaignId'
        /// </summary>
        [Fact]
        public void EmailCampaignIdTest()
        {
            // TODO unit test for the property 'EmailCampaignId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'SubaccountId'
        /// </summary>
        [Fact]
        public void SubaccountIdTest()
        {
            // TODO unit test for the property 'SubaccountId'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'ListId'
        /// </summary>
        [Fact]
        public void ListIdTest()
        {
            // TODO unit test for the property 'ListId'
        }

        /// <summary>
        /// Test the property 'FromEmailAddressId'
        /// </summary>
        [Fact]
        public void FromEmailAddressIdTest()
        {
            // TODO unit test for the property 'FromEmailAddressId'
        }

        /// <summary>
        /// Test the property 'FromName'
        /// </summary>
        [Fact]
        public void FromNameTest()
        {
            // TODO unit test for the property 'FromName'
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Fact]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'DateAdded'
        /// </summary>
        [Fact]
        public void DateAddedTest()
        {
            // TODO unit test for the property 'DateAdded'
        }

        /// <summary>
        /// Test the property 'CustomString'
        /// </summary>
        [Fact]
        public void CustomStringTest()
        {
            // TODO unit test for the property 'CustomString'
        }

        /// <summary>
        /// Test the property 'SendCount'
        /// </summary>
        [Fact]
        public void SendCountTest()
        {
            // TODO unit test for the property 'SendCount'
        }

        /// <summary>
        /// Test the property 'OpenCount'
        /// </summary>
        [Fact]
        public void OpenCountTest()
        {
            // TODO unit test for the property 'OpenCount'
        }

        /// <summary>
        /// Test the property 'ClickCount'
        /// </summary>
        [Fact]
        public void ClickCountTest()
        {
            // TODO unit test for the property 'ClickCount'
        }

        /// <summary>
        /// Test the property 'HardBounceCount'
        /// </summary>
        [Fact]
        public void HardBounceCountTest()
        {
            // TODO unit test for the property 'HardBounceCount'
        }

        /// <summary>
        /// Test the property 'SoftBounceCount'
        /// </summary>
        [Fact]
        public void SoftBounceCountTest()
        {
            // TODO unit test for the property 'SoftBounceCount'
        }

        /// <summary>
        /// Test the property 'AbuseCount'
        /// </summary>
        [Fact]
        public void AbuseCountTest()
        {
            // TODO unit test for the property 'AbuseCount'
        }

        /// <summary>
        /// Test the property 'UnsubscribeCount'
        /// </summary>
        [Fact]
        public void UnsubscribeCountTest()
        {
            // TODO unit test for the property 'UnsubscribeCount'
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'BodyPlainText'
        /// </summary>
        [Fact]
        public void BodyPlainTextTest()
        {
            // TODO unit test for the property 'BodyPlainText'
        }
    }
}
