/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ClickSend.Model;
using ClickSend.Client;
using System.Reflection;

namespace ClickSend.Test.Model
{
    /// <summary>
    ///  Class for testing GetTrackingDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetTrackingDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetTrackingDataInner
        //private GetTrackingDataInner instance;

        public GetTrackingDataInnerTests()
        {
            // TODO uncomment below to create an instance of GetTrackingDataInner
            //instance = new GetTrackingDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetTrackingDataInner
        /// </summary>
        [Fact]
        public void GetTrackingDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetTrackingDataInner
            //Assert.IsType<GetTrackingDataInner>(instance);
        }

        /// <summary>
        /// Test the property 'OpenCount'
        /// </summary>
        [Fact]
        public void OpenCountTest()
        {
            // TODO unit test for the property 'OpenCount'
        }

        /// <summary>
        /// Test the property 'DateOpened'
        /// </summary>
        [Fact]
        public void DateOpenedTest()
        {
            // TODO unit test for the property 'DateOpened'
        }

        /// <summary>
        /// Test the property 'UserGeoCountry'
        /// </summary>
        [Fact]
        public void UserGeoCountryTest()
        {
            // TODO unit test for the property 'UserGeoCountry'
        }

        /// <summary>
        /// Test the property 'UserGeoRegion'
        /// </summary>
        [Fact]
        public void UserGeoRegionTest()
        {
            // TODO unit test for the property 'UserGeoRegion'
        }

        /// <summary>
        /// Test the property 'UserDevice'
        /// </summary>
        [Fact]
        public void UserDeviceTest()
        {
            // TODO unit test for the property 'UserDevice'
        }

        /// <summary>
        /// Test the property 'UserBrowser'
        /// </summary>
        [Fact]
        public void UserBrowserTest()
        {
            // TODO unit test for the property 'UserBrowser'
        }

        /// <summary>
        /// Test the property 'UserOs'
        /// </summary>
        [Fact]
        public void UserOsTest()
        {
            // TODO unit test for the property 'UserOs'
        }

        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Fact]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
    }
}
