/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ClickSend.Model;
using ClickSend.Client;
using System.Reflection;

namespace ClickSend.Test.Model
{
    /// <summary>
    ///  Class for testing OwnNumber
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OwnNumberTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OwnNumber
        //private OwnNumber instance;

        public OwnNumberTests()
        {
            // TODO uncomment below to create an instance of OwnNumber
            //instance = new OwnNumber();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OwnNumber
        /// </summary>
        [Fact]
        public void OwnNumberInstanceTest()
        {
            // TODO uncomment below to test "IsType" OwnNumber
            //Assert.IsType<OwnNumber>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'WorkspaceId'
        /// </summary>
        [Fact]
        public void WorkspaceIdTest()
        {
            // TODO unit test for the property 'WorkspaceId'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'VerifiedTimestamp'
        /// </summary>
        [Fact]
        public void VerifiedTimestampTest()
        {
            // TODO unit test for the property 'VerifiedTimestamp'
        }

        /// <summary>
        /// Test the property 'NotifiedTimestamp'
        /// </summary>
        [Fact]
        public void NotifiedTimestampTest()
        {
            // TODO unit test for the property 'NotifiedTimestamp'
        }

        /// <summary>
        /// Test the property 'IsNearingExpiration'
        /// </summary>
        [Fact]
        public void IsNearingExpirationTest()
        {
            // TODO unit test for the property 'IsNearingExpiration'
        }

        /// <summary>
        /// Test the property 'CreatedTimestamp'
        /// </summary>
        [Fact]
        public void CreatedTimestampTest()
        {
            // TODO unit test for the property 'CreatedTimestamp'
        }

        /// <summary>
        /// Test the property 'UpdatedTimestamp'
        /// </summary>
        [Fact]
        public void UpdatedTimestampTest()
        {
            // TODO unit test for the property 'UpdatedTimestamp'
        }
    }
}
