/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ClickSend.Model;
using ClickSend.Client;
using System.Reflection;

namespace ClickSend.Test.Model
{
    /// <summary>
    ///  Class for testing SendPostcardRequestRecipientsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendPostcardRequestRecipientsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendPostcardRequestRecipientsInner
        //private SendPostcardRequestRecipientsInner instance;

        public SendPostcardRequestRecipientsInnerTests()
        {
            // TODO uncomment below to create an instance of SendPostcardRequestRecipientsInner
            //instance = new SendPostcardRequestRecipientsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendPostcardRequestRecipientsInner
        /// </summary>
        [Fact]
        public void SendPostcardRequestRecipientsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendPostcardRequestRecipientsInner
            //Assert.IsType<SendPostcardRequestRecipientsInner>(instance);
        }

        /// <summary>
        /// Test the property 'AddressName'
        /// </summary>
        [Fact]
        public void AddressNameTest()
        {
            // TODO unit test for the property 'AddressName'
        }

        /// <summary>
        /// Test the property 'AddressCity'
        /// </summary>
        [Fact]
        public void AddressCityTest()
        {
            // TODO unit test for the property 'AddressCity'
        }

        /// <summary>
        /// Test the property 'AddressState'
        /// </summary>
        [Fact]
        public void AddressStateTest()
        {
            // TODO unit test for the property 'AddressState'
        }

        /// <summary>
        /// Test the property 'AddressPostalCode'
        /// </summary>
        [Fact]
        public void AddressPostalCodeTest()
        {
            // TODO unit test for the property 'AddressPostalCode'
        }

        /// <summary>
        /// Test the property 'AddressCountry'
        /// </summary>
        [Fact]
        public void AddressCountryTest()
        {
            // TODO unit test for the property 'AddressCountry'
        }

        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Fact]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }

        /// <summary>
        /// Test the property 'ReturnAddressId'
        /// </summary>
        [Fact]
        public void ReturnAddressIdTest()
        {
            // TODO unit test for the property 'ReturnAddressId'
        }
    }
}
