/*
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ClickSend.Model;
using ClickSend.Client;
using System.Reflection;

namespace ClickSend.Test.Model
{
    /// <summary>
    ///  Class for testing ViewAvailableNumbersDataAllOfDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ViewAvailableNumbersDataAllOfDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ViewAvailableNumbersDataAllOfDataInner
        //private ViewAvailableNumbersDataAllOfDataInner instance;

        public ViewAvailableNumbersDataAllOfDataInnerTests()
        {
            // TODO uncomment below to create an instance of ViewAvailableNumbersDataAllOfDataInner
            //instance = new ViewAvailableNumbersDataAllOfDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ViewAvailableNumbersDataAllOfDataInner
        /// </summary>
        [Fact]
        public void ViewAvailableNumbersDataAllOfDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ViewAvailableNumbersDataAllOfDataInner
            //Assert.IsType<ViewAvailableNumbersDataAllOfDataInner>(instance);
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'CountryName'
        /// </summary>
        [Fact]
        public void CountryNameTest()
        {
            // TODO unit test for the property 'CountryName'
        }

        /// <summary>
        /// Test the property 'DedicatedNumber'
        /// </summary>
        [Fact]
        public void DedicatedNumberTest()
        {
            // TODO unit test for the property 'DedicatedNumber'
        }

        /// <summary>
        /// Test the property 'PriceSetup'
        /// </summary>
        [Fact]
        public void PriceSetupTest()
        {
            // TODO unit test for the property 'PriceSetup'
        }

        /// <summary>
        /// Test the property 'PriceMonthly'
        /// </summary>
        [Fact]
        public void PriceMonthlyTest()
        {
            // TODO unit test for the property 'PriceMonthly'
        }

        /// <summary>
        /// Test the property 'PriceTotal'
        /// </summary>
        [Fact]
        public void PriceTotalTest()
        {
            // TODO unit test for the property 'PriceTotal'
        }

        /// <summary>
        /// Test the property 'AddressRequirement'
        /// </summary>
        [Fact]
        public void AddressRequirementTest()
        {
            // TODO unit test for the property 'AddressRequirement'
        }
    }
}
